### ISSUE TITLE
Msbuildify tools

### ISSUE THREAD

**Issue by muratg** [aspnet/DotNetTools#161]
### Microsoft.DotNet.Watcher.Tools
- Expect to run independently, via the CLI
- Project “inputs”: Source files, resource files, etc.
- Needs to know the literal globs so it can identify folders to watch
- P2P graph
### Microsoft.Extensions.SecretManager.Tools

Expect to run independently, via the CLI
userSecretId is in MSBuild or a config file, generated a config file in output or assembly attribute?
No runtime dependency on the project file!
### TODO
- Fork tools repos to `rel/1.0.0-preview3` branches for "October" release. Dev branches will continue to be used for 1.1 release.
- Use desktop msbuild to start our work until the new msbuild is ready for   consumption
### Notes
- [This](https://github.com/aspnet/Coherence-Signed/issues/375) tracks the work across the tools repos.
- [This](https://github.com/aspnet/specs/blob/master/notes/Tools.md) is the previous discussion on the topic.

**Comment by natemcmaster** [comment]
From #156 
-----------
project.json and Microsoft.DotNet.ProjectModel are being retired in favor of xplat MSBuild. dotnet-watch should update to support the new project system for dotnet-cli.

Open questions

 - How should we interpret the project system to discover files to watch? Two options:
    1. Make dotnet-watch an msbuild task
    2. Host MSBuild and execute a design-time build to discover items and properties
 - Can we ensure we detect files are added when MSBuild uses globs?
 - Can we reuse components from https://github.com/dotnet/roslyn-project-system to do this?

**Comment by sayedihashimi** [comment]
@natemcmaster any progress here? We depend on this feature in VS Templates. Minimally we need to know the file location where the tool will be looking for the secrets.

**Comment by natemcmaster** [comment]
We are still waiting on design decisions from MSBuild before we proceed, but if this is blocking you let's talk more in detail. I may be able to provide enough concrete details to unblock you.

**Comment by sayedihashimi** [comment]
@natemcmaster thanks. Please chat with @abpiskunov or @mlorbetske.

**Comment by natemcmaster** [comment]
Some progress from MSBuild: https://github.com/Microsoft/msbuild/pull/1080. This will help us as we build tools that need to perform project evaluation.

**Comment by natemcmaster** [comment]
Blocked by https://github.com/dotnet/cli/issues/4213

**Comment by muratg** [comment]
@natemcmaster good to close?

**Comment by natemcmaster** [comment]
Yes, basic work is done now.
