### ISSUE TITLE
Add user-secret init command

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#166]
_From @Tratcher on December 10, 2015 18:37_

When you try to use user-secret on a new project it fails with:
`critical: Command failed : Missing 'userSecretsId' in 'C:\git\Universe\Security\samples\JwtBearerSample\project.json'`

There should be an `init` command to generate the userSecretsId in the project.json.

_Copied from original issue: aspnet/UserSecrets#53_

**Comment by natemcmaster** [comment]
Relevant work on CLI: https://github.com/dotnet/cli/issues/4746

**Comment by natemcmaster** [comment]
Remarking for triage: as this should be trivial now that preview5 of CLI has built infrastructure for this. `dotnet user-secrets init` could easily shell out to `dotnet add package Microsoft.Extensions.Configuration.UserSecrets`

**Comment by muratg** [comment]
Depends on https://github.com/dotnet/cli/issues/5300

**Comment by liamdawson** [comment]
@muratg would you be interested in a more naive implementation until dotnet/cli#5300 is complete?

**Comment by natemcmaster** [comment]
@liamdawson depends on how it was implemented. Can you share a brief description of how you would implement this?

**Comment by liamdawson** [comment]
Certainly.

* Add a command called `init`
    * Support a `--force` flag to force resetting the secrets ID
* `init` uses the `MsBuildProjectFinder` class to find the project file
* Parse the project file as XML, check if any of the `<PropertyGroup>` elements contain a `<UserSecretsId />`
    * If not, add one with a new `Guid` to the first `<PropertyGroup>`
    * If exists and not `--force`, exit with an error
    * If exists and `--force`, set a new `Guid` on the existing `<UserSecretsId />`

I'm sure I'm missing intricacies of the MS Build system, but I think that would be sufficient for the typical `dotnet new` project, at least?

**Comment by natemcmaster** [comment]
Yes, I think its safe to treat the file as XML. _Technically,_ it would be better to use the API in [Microsoft.Build.Construction](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction?view=netframework-4.7) namespace, but we have avoided adding MSBuild references to our CLI tools for a handful of reasons. XML should be OK for this purpose.

A few additions:
 - The command already has a global flag for `--id`. If set, use this value instead of generating a guid. (see [CommandLineOptions.Id](https://github.com/aspnet/DotNetTools/blob/daa928de92d9ce5df73350d7b428ca1a951947d4/src/Microsoft.Extensions.SecretManager.Tools/CommandLineOptions.cs#L15))
 - Make sure the `PropertyGroup` group does not have a `Condition` attribute.
 - Print command line instructions to the console instructing user to install the `Microsoft.Extensions.Configuration.UserSecrets` package.

If a PR met these requirements and had tests, I'd accept it.

As an alternative to the last suggestion, you could also automatically install the package reference using `dotnet add package`. (Provide an opt-out flag like `--no-install`). This is a little more difficult to get right, so I'm not sure yet if we want to take this yet. But if you did, it might look like this...

- Check first that the package isn't already installed. In .NET Core 2.0, most dotnet new projects will reference Microsoft.AspNetCore.All which will bring in the package. If not installed yet,
   - Install the latest 1.0.x package in .NET Core 1.0 projects
   - Install 1.1.x in .NET Core 1.1, .NET Framework < 4.6.1, and .NET Standard 1.x projects
   - Install 2.0.0 in .NET Core 2.0, .NET Framework >= 4.6.1, and .NET Standard 2.x projects

**Comment by muratg** [comment]
Backlogging. We'd still be interested in taking a PR for this.

**Comment by DamianEdwards** [comment]
Would love to see this happen.

**Comment by natemcmaster** [comment]
The problem in the past was that we needed Microsoft.Build.Construction align with whatever the SDK bundled. There was no easy way to do that. Now that dotnet-user-secrets is bundled in the SDK, we can ensure these align, so the implementation shouldn't be as difficult any more.

**Comment by spboyer** [comment]
Why don't we just add the <UserSecrets> node to every project? Is there a danger?

**Comment by natemcmaster** [comment]
There is a general desire not to add things to projects until required. We add UserSecretsId to new projects under some conditions (see [this for example](https://github.com/aspnet/templating/blob/cb3581869b3d6d4d63650a06f1dd5b46bba7442e/src/Microsoft.DotNet.Web.ProjectTemplates/WebApi-CSharp.csproj.in#L6)) and VS should add it when you invoked the user secrets UI.

**Comment by spboyer** [comment]
Agreed, but all of that falls down when we are not using VS. Right-Click, what happens in right click stays in right click...

Need better/parity experiences for non visual studio users and command line users.

**Comment by natemcmaster** [comment]
Agreed. It's been asked about a few times in the last few years, but has never seemed high enough priority to tackle. That's why this is up-for-grabs :) I'm open to accepting a PR for this in 2.2 (provided we take into consideration the comments I made above in https://github.com/aspnet/DotNetTools/issues/166#issuecomment-314507374)

**Comment by liamdawson** [comment]
I'm _finally_ getting around to doing this now, for entirely altruistic reasons... 😇
Should I be targetting the 2.2 branch, and using MSBuild references now?

**Comment by Tratcher** [comment]
indeed, the release/2.2 branch

**Comment by liamdawson** [comment]
I've run into some issues based on `SecretsStore` being expected for all commands:

* If an ID isn't successfully found, the application exits before init can be called.
* If I wrap the `SecretStore` in a `Lazy<T>` which throws the error, it breaks the calling conventions of the application somewhat.
* Assuming I manage to fix that issue, I'd want to return errors in the same format as initializing the `SecretStore` does when anything _except_ ProjectId missing occurs for reading the project file.

I've put together some commits where I can demonstrate that (some `SecretManagerTests` cases fail), which gets to the point where the `InitCommand` can be called and it has access to the working directory, but I'm concerned about how tangled any future work is going to get.

For reference, see [this commit](https://github.com/liamdawson/DotNetTools/commit/0ffb0ae581394dac93ce7fdd2f8cc6efea043085) and its parent.

Any thoughts on how I should proceed?

**Comment by natemcmaster** [comment]
What if you started by putting the init command here: https://github.com/aspnet/DotNetTools/blob/60041b5b2bcb84a9a6b9eb460f6e395a270934c8/src/dotnet-user-secrets/Program.cs#L67-L80

For example,

```diff
var reporter = CreateReporter(options.IsVerbose);

+ if (options.Command is InitCommand initCmd)
+ {
+     return initCmd.Execute(new CommandContext());
+ }

string userSecretsId;
try
{
    userSecretsId = ResolveId(options, reporter);
}
```

**Comment by liamdawson** [comment]
Yeah, slightly embarrassed I didn't think of that option. Thanks, I'll try that out soon!

**Comment by natemcmaster** [comment]
Closing as resolved with https://github.com/aspnet/DotNetTools/pull/500

Thanks @liamdawson for the contribution!
