### ISSUE TITLE
Make tool more friendly in usage from other tooling.

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#168]
_From @phenning on August 24, 2016 20:9_

For example, in order to display a grid, you would need to parse out the info: output from the results of dotnet user-secrets list. Ideally, this should just be a --json or similar switch which would just output the secrets as json.

Similarly, it would also be good to be able to pass in json via the set command, bonus if nested json could be passed in here and the tool would take care of flattening. 

_Copied from original issue: aspnet/UserSecrets#95_

**Comment by muratg** [comment]
@glennc @Eilon do we want to take this in 1.1? @natemcmaster already has a PR which I started reviewing...

**Comment by Eilon** [comment]
Rendering as JSON would be nice, I guess, though I don't see why it's a high priority. Taking in JSON in the command line seems odd - what's the scenario for that?

**Comment by natemcmaster** [comment]
Consider this a "delighter feature". JSON rendering was a trivial addition. The reading JSON part is more involved, but I built it for myself cause I was tired of manually setting secrets one by one. This makes it easy to quickly add many secrets using the CLI tool without manually writing to the secrets.json file in %LOCALAPPDATA%.

@phenning made a similar request in aspnet/UserSecrets#95 :

> Similarly, it would also be good to be able to pass in json via the set command, bonus if nested json could be passed in here and the tool would take care of flattening.
