### ISSUE TITLE
Store UserSecretsId in MSBuild project file instead of project.json

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#169]
_From @muratg on August 24, 2016 22:43_

Slightly related #62. 

Since project.json is going away, we'll need to resolve this soon.

@glennc @davidfowl @natemcmaster @Tratcher 

_Copied from original issue: aspnet/UserSecrets#96_

**Comment by natemcmaster** [comment]
Just brainstorming: here are some options

 - A special purpose setting file,`usersecrets.json`, in project root. Works the same as project.json does today. Ms.Ext.Config.UserSecrets [extends the build target](https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project) to ensure the file is copied to build folder.
 - A general setting file, like `appsettings.json` (or `web.config` :trollface: )
 - A well-known MSBuild property `<UserSecretId>XXXX-XXXX</UserSecretId>`
    - Requires adding a target to generate a resource for config to read at runtime such as
       - an assembly attribute
       - a config file in app base dir
    - CLI tool
        - runs inside build: `dotnet user-secrets` becomes alias for `dotnet msbuild /t:UserSecrets`
        - otherwise, CLI tool hosts MSBuild and does a [design time build](https://github.com/dotnet/roslyn-project-system/blob/7463c45b7f3bdf851f8da157f7b65236f87102c2/docs/design-time-builds.md) to extract the property value. (See [early implementation](https://github.com/aspnet/EntityFramework/blob/65ef9a6c53e077e0028a32ef4b3029b31ec0728c/src/Tools.DotNet/Internal/MsBuildProjectContext.cs) of something similar in dotnet-ef)

**Comment by natemcmaster** [comment]
_From @glennc on August 30, 2016 6:4_

msbuild seems the best option here. But why does there need to be a special file generated? Why can there not be a config source that reads from a csproj?

It is just data in the csproj.

**Comment by natemcmaster** [comment]
_From @Tratcher on August 30, 2016 14:14_

The csproj isn't published

**Comment by natemcmaster** [comment]
IMO keeping the id in a simple file such as `usersecrets.json` or `.usersecretrc` is the better option. Adding as a property in MSBuild is going to be more complicated and have little benefit

**Comment by natemcmaster** [comment]
_From @davidfowl on August 30, 2016 16:44_

What about `appsettings.json` and we pass the filename into the `AddUserSecrets`. It's a bit of a breaking change though but it seems like a cleaner approach

**Comment by natemcmaster** [comment]
Did a quick spike: here's what something like `usersecrets.json` would look like https://github.com/aspnet/UserSecrets/compare/namc/usersecrets.json.

I'm guessing some may complain "why the extra file in my project?". If users care, we could overload `AddUserSecrets` to allow specifying a path to `appsettings.json` or something else.

**Comment by natemcmaster** [comment]
Design from in-person discussion with @glennc and @davidfowl:

1. The value of userSecretId can be in any json file. Templates and tools will default to a file named `appsettings.json`. Users could configure it to 'project.json' if they still want

   ```json
   {
       "userSecretId": "xxxx-xxxx"
   }
   ```

1. `[assembly: UserSecretIdentifierFileNameAttribute("appsettings.json")]` will be generated during build using a task imported from the `Microsoft.Extensions.Configuration.UserSecrets` nupkg. The value of the attribute is configured from a property in the csproj. This will be in templates. It will default to appsettings.json if not present.
    ```xml
    <PropertyGroup>
        <UserSecretIdentifierFile>appsettings.json</UserSecretIdentifierFile>
    </PropertyGroup>
    ```
1. Runtime: `.AddUserSecrets()` will look for an assembly attribute, `Assembly.GetEntryAssembly().GetCustomAttribute<UserSecretIdentifierFileNameAttribute>().FileName` and read **userSecretId** from the json file. As with other config files, we will assume the path is relative to `ConfigurationBuilder.GetFileProvider()`.
1. Design-time tooling: VS can identify which file to use by evaluating the csproj. CLI can take a command line flag to point to a different JSON file.

**Comment by natemcmaster** [comment]
_From @muratg on September 13, 2016 17:31_

Will the attribute be a top-level attribute in the Json file (as it is today?)

**Comment by natemcmaster** [comment]
Yes. The JSON part of this doesn't change much. We are just going to remove the strict requirement that the JSON file be named project.json. (See #103)

**Comment by hlubovac** [comment]
Before I decided to finally ask the question that follows, I looked at the source code to find references to what you're talking about. The problem that I'm trying to solve for myself is storing the userSecretsIs outside of project.json, preferably totally abstracted away from the SecretManager.Tools package, so that it's [alternatively to its known locations] delivered to the tool via CLI arguments. I can't see that the tool code supports that (https://github.com/aspnet/DotNetTools/blob/11bbd6df8e363d87b7f5498b8491e085d90be5d1/src/Microsoft.Extensions.SecretManager.Tools/Program.cs#L137), although it doesn't seem to me that it'd be hard to implement.

The SecretManager's `AddUserSecrets` method already accepts userSecretsId as an alternative to assumption that that value lives in project.json, which is good. That enables me to store it where I want to (file, env-var, to mention a few). So, what's missing now it the Tools package to follow, as opposed to continue looking for it in project.json.

I couldn't find that asm attribute (UserSecretIdentifierFileNameAttribute) to even try pointing to another file, which makes me curious if what you're talking about made it to the repository or if it lives in another package (I don't see why it would, though).

Unrelated, but, IMO, this secret-identifier is a part of configuration, and it shouldn't even be discussed - beyond config-transformations - how to automate moving it via MSBuild: that value, along with associated "secrets" shouldn't cross business-environment boundaries anyway and they all should be defined manually, one time per machine-environment pair.

Thanks.

**Comment by natemcmaster** [comment]
@hlubovac This is a WIP. I've added `--id <ID>` to the CLI tool in the feature/msbuild branch. (see https://github.com/aspnet/DotNetTools/blob/27fc53ea16404820bb039fbaaca5f847c8819a31/src/Microsoft.Extensions.SecretManager.Tools/Internal/CommandLineOptions.cs#L42-L45). UserSecretIdentifierFileNameAttribute was never implemented. We decided to go with the plan in my most recent comment: https://github.com/aspnet/DotNetTools/issues/169#issuecomment-252080498

> this secret-identifier is a part of configuration

The actual content of the ID doesn't matter for most people. But the problem we're trying to address is "where is it stored?" We chose the project file because it unifies the Visual Studio, CLI tools, and the runtime experience.

**Comment by hlubovac** [comment]
Thanks. Do you think it'll be long before that change makes it to master/nuget?

**Comment by natemcmaster** [comment]
I don't have a date. We're waiting on dotnet/cli 's MSBuild to stabilize. But, '--id' would be easy enough to add to the version on dev branch that I'd happily take a PR to added it now if it'll unblock you.

**Comment by hlubovac** [comment]
No, it's fine; I can wait. I'm experimenting anyway, with no particular plan in mind. I don't want to distract you from your current goal. Thank you, though.

**Comment by hlubovac** [comment]
A hack, as an alternative solution to storing this value in a separate file:
1. create a subdirectory within your project (e.g. "blah")
2. create blah\project.json file; add userSecretsId value to it using established format
3. This and similar should then work:
dotnet user-secrets list --project "[full-path-to]\aspnetcoreapp\blah"

**Comment by natemcmaster** [comment]
One of the unintended consequences of this design https://github.com/aspnet/DotNetTools/issues/169#issuecomment-252080498 is https://github.com/aspnet/Configuration/issues/543. Any design-time tooling that invokes 'Startup' is likely to break.

**Comment by natemcmaster** [comment]
The work for this is done. When released, the feature will be in the following packages:

Microsoft.Extensions.SecretManager.Tools (1.0.0-msbuild1-final)
Microsoft.Extensions.Configuration.UserSecrets (≥ 1.0.1)
