### ISSUE TITLE
Disable dotnet watch within Visual Studio

### ISSUE THREAD

**Issue by jasselin** [aspnet/DotNetTools#176]
Could you provide a way to disable dotnet watch when using Visual Studio?

I have a case where I don't want to rebuild a project when changing any cs files.

Thanks

**Comment by victorhurdugaci** [comment]
`dotnet watch` is not enabled in VS. Actually, VS doesn't know at all about `watch`

**Comment by jasselin** [comment]
I tought the feature that rebuilds the solution when hitting F5 was dotnet watch.
Do you know any way to disable it? Should I ask the Visual Studio tooling folks?

**Comment by victorhurdugaci** [comment]
Nope, that's not `watch`. @troydai or @BillHiebert might know if disabling that is possible. I think it comes from the DTH

**Comment by muratg** [comment]
This issue was moved to aspnet/Tooling#793
