### ISSUE TITLE
Remove DotNetCoreSdkResolver

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#182]
Current tool prototypes use the existence of MSBuild inside the .NET Core SDK to do project evaluation. We did this to unblock our prototype development, but this API is fragile and not a good long-term solution.

Opening this to track work towards a long-term solution.

Possible solutions:
 - MSBuild support for https://github.com/Microsoft/msbuild/issues/1097 (preferred)
 - Add API to CLI utils to locate SDK

cc @piotrpMSFT @jeffkl

**Comment by natemcmaster** [comment]
CLI will be adding an environment variable pointing to the location of MSBuild. When this becomes available, we should be able to remove the SDK resolver.

**Comment by jeffkl** [comment]
FYI @AndyGerlicher and @rainersigwald
