### ISSUE TITLE
[dotnet-watcher] Need for DOTNET_WATCHER_EXIT_ON_CHANGE or equivalent

### ISSUE THREAD

**Issue by saikatguha** [aspnet/DotNetTools#186]
I have multiple dotnet projects that are composed together by running in parallel.
They share common library code.

When any change is made to the library, all the watchers attempt to recompile. Due to contention some of the re-compiles fail. `dotnet watch` assumes the compilation failure is fatal (which it is not) and goes back to watching for more changes. When something changes, all the watchers race to compile, and some again fail. The end result is that the app is never recomposed.

If `dotnet watch` could exit instead of all racing to recompile the same code, I can restart the watch after a random delay in the surrounding shell script. There used to be a `--exit-on-change` option, which was removed in Commit #63bbafdb to simply arguments handling.

Can we add the exit on change functionality back in, controlled perhaps by an environment variable or something?

**Comment by natemcmaster** [comment]
At the moment, we're being very tentative about adding command line flags. We're working to port dotnet-watch to support MSBuild projects. When we get that working well, we will examine again whether it makes since to make options such your suggestion available via the options in the MSBuild file itself, as a command line flag itself, or both.

**Comment by muratg** [comment]
I'm guessing the new solution to https://github.com/aspnet/DotNetTools/issues/319 would help in this scenario. @natemcmaster do you agree? If so, this can be closed.

**Comment by natemcmaster** [comment]
Re-reading this, I'm not sure I completely understand the scenario. @saikatguha are you trying to watch multiple projects and execute a command on **all** of those projects when any of them change? Or are you trying to watch multiple projects and execute a command on **one** of those projects? #319 might cover the latter scenario.

**Comment by saikatguha** [comment]
My scenario is as follows:
libraryX referenced by executableA
libraryX referenced by executableB

dotnet watch run executableA &
dotnet watch run executableB

...

Make edit to libraryA.
Both watches exit and try to (simultaneously) recompile libraryA.
One succeeds and the other fails due to compiler lock.
Say executableA recompile succeeds and executableB fails.

dotnet watch restarts executableA
however, dotnet watch executableB (in broken state) goes back to watching for more changes (even through executableB could not be re-compiled). As a result, executableB does not come back up.

**Comment by natemcmaster** [comment]
I'm closing because we don't currently have plans to implement changes to dotnet-watch for this scenario.
