### ISSUE TITLE
Support Localization Resource Generation & Translation

### ISSUE THREAD

**Issue by hishamco** [aspnet/DotNetTools#203]
Last few days I started a new `dotnet` CLI tool to generate and translate localization resources called `dotnet resgen` this is the link to my repo https://github.com/hishamco/LocalizationResourceGenerator, it would be nice to support such utility tool during the development phase on all the localization web applications.
FYI the tool is under development, and may it needs a lot of improvements by the time

/cc @Eilon

**Comment by hishamco** [comment]
@natemcmaster is this the right repo for such tool?!!

**Comment by natemcmaster** [comment]
I'm not aware of any official plans to create or support such a tool. 

But, I'm happy to provide pointers if you have more questions. Also, as you probably know, https://github.com/dotnet/cli is the "home" of most discussion related to CLI tools.

**Comment by hishamco** [comment]
Thanks

**Comment by Eilon** [comment]
Yeah, no plans to ship this as part of ASP.NET...

**Comment by hishamco** [comment]
@Eilon is there a repo for AspNetCoreContrib so we can contribute an official stuff that may developers need?

**Comment by natemcmaster** [comment]
@hishamco have you seen https://github.com/aspnet-contrib? This isn't run by us, but sounds like what you're looking for.

**Comment by hishamco** [comment]
Thanks @natemcmaster, I already saw this repo, but I don't how can create or suggest new project or idea
