### ISSUE TITLE
Create a version of dotnet-watch that is independent of build system in use

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#204]
**Background**
dotnet-watch is currently depends on the project.json (PJ) to decide which files to watch. With the deprecation of PJ, we lose the ability to easily interpret a project model and identify which files to watch. The .NET SDK for MSBuild doesn't have an API to enhance dotnet-watch to understand this system without being a part of it. 

Instead of enhancing dotnet-watch to understand this complex build system, dotnet-watch should be decoupled from it. I expect this approach can still achieve the same result, but deliver it will lower complexity, bugs, and higher flexibility.

**Proposals**

**1.** 
dotnet-watch will not attempt to parse/interpret .csproj files. It will also drop support for reading project.json files.

**2.**
dotnet-watch can be configured by a file "watch.json" to determine which files to include/exclude. This file's directory is the "watch root".

``` json
{
    "files": {
        "include": [],
        "exclude": []
    }
}

```

**3.**
In absence of a watch.json file, dotnet-watch will attempt to the watch root.
1. Walk up folder structure to the nearest watch.json
2. Walk up to nearest .sln file.
3. Run in current directory using default globbing patterns (see next item).

**4.**
In absence of a watch.json file, it uses some defaults globbing patterns.

```
Include
**/*.cs
**/*.resx
**/*.csproj

Exclude
bin/
obj/
files/directories that start with a period
```

**5.**
Add a command "dotnet watch init" which will a local copy of "watch.json" prepopulated with the defaults.

**6.**
All other command line syntax remains the same. Example: `dotnet watch run` should still watch all *.cs files and attempt to do "dotnet run" when they change.

**Comment by natemcmaster** [comment]
cc @glennc @muratg @davidfowl

**Comment by muratg** [comment]
cc @DamianEdwards

**Comment by natemcmaster** [comment]
I think at this point we've ruled out this option. We're invested in making the MSBuild integration work.

**Comment by mikeesouth** [comment]
@natemcmaster What do you mean by "ruled out this option"? `dotnet watch` was a great benefit of PJ, is it just being "ruled out" due to the MSBuild integration? Are there any options here?

**Comment by natemcmaster** [comment]
As we began to port dotnet-watch from project.json to MSBuild, we considered (as described above) a variant the tool that didn't attempt to parse project.json or MSBuild, but was instead configured via 'watch.json' or something else. We decided not to do this, however, in favor of building MSBuild integration into dotnet-watch. The goal of our MSBuild integration was to basically preserve the dotnet-watch + project.json behavior. i.e. most users can run `dotnet watch run` in your project directory...no additional configuration required.

Also, FWIW, we've ported dotnet-watch to support *.csproj files. You can give a pre-release a try by installing this into your csproj:

```xml
<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0-msbuild2-final" />
</ItemGroup>
```

**Comment by mikeesouth** [comment]
Thanks @natemcmaster, that's excellent news. I added the reference into my .csproj file and it worked perfectly. *thumbs up*

**Comment by natemcmaster** [comment]
Awesome news @mikeesouth :) Please don't hesitate to open issues to ask questions or report bugs as we're preparing to final 1.0.0 release soon.
