### ISSUE TITLE
dotnet-watch: show example usages in help message

### ISSUE THREAD

**Issue by cesarbs** [aspnet/DotNetTools#205]
Current message:

`Usage: dotnet watch [options] [[--] <arg>...]`

Should be

`Usage: dotnet watch COMMAND [options] [[--] <arg>...]`

Command being `run`, `test` i.e. a `dotnet` command.

**Comment by natemcmaster** [comment]
*Technically, the current message is accurate, but I'm guessing you (and others) won't realize that `[[--] <arg>...]` means "put run/test/etc here". Probably could be helped by adding an example to the help message.

**Comment by cesarbs** [comment]
I don't really get that from `[[--] <arg>...]`. That part of the usage message is saying "if you want to pass args to the command being watched, use `--` followed by the command's args.

**Comment by natemcmaster** [comment]
The command goes after the (optional) `--` separator. Examples of correct usage:
`dotnet watch run arg1 arg2`
`dotnet watch -- run arg1 arg2`
`dotnet watch -- test -class A.B.Test`.

FWIW, it's matches what the CLI does:

![image](https://cloud.githubusercontent.com/assets/2696087/19569795/de6d32c0-96ab-11e6-9101-3f8379fd4f32.png)

But I think this is a good ask: the default help message isn't super obvious

**Comment by cesarbs** [comment]
That's not what's documented here: https://github.com/aspnet/DotNetTools/tree/dev/src/Microsoft.DotNet.Watcher.Tools

**Comment by natemcmaster** [comment]
I don't see the difference. Let's talk in person.

**Comment by muratg** [comment]
Looks like this was done. Good to close?

**Comment by natemcmaster** [comment]
No, it's not done yet.
