### ISSUE TITLE
Combining dotnet watch and a Vagrant synced_folder does not work

### ISSUE THREAD

**Issue by DonSchenck** [aspnet/DotNetTools#219]
Environment: Running Red Hat Enterprise Linux (RHEL) in a VM on my Windows 10 machine, using Vagrant to manage a VM in Virtual Box.

Using the Vagrant "synced_folder" option, I can share a folder between the host (Windows 10) machine and the guest (RHEL) machine.

If, after starting `dotnet watch run` on the RHEL machine, you make changes from the Windows machine (using, for example, Visual Studio Code), dotnet watch *does not* see the changes.

Making changes from within the VM (using, for example, VI) *does* work.

**Comment by natemcmaster** [comment]
Are you using the environment variable DOTNET_USE_POLLING_FILE_WATCHER=1? https://github.com/aspnet/DotNetTools/tree/dev/src/Microsoft.DotNet.Watcher.Tools#environment-variables

**Comment by DonSchenck** [comment]
OMG YOU'RE A GENIUS! THANK YOU!

Seriously; thanks.

**Comment by natemcmaster** [comment]
Ah shucks, thanks :). 

Question: would a command line switch have been more discoverable? e.g. did you ever do `dotnet watch --help`?

**Comment by DonSchenck** [comment]
`foo --help` is pretty much how I learn everything, so yeah ... that would be great.

**Comment by DonSchenck** [comment]
What if we simply add the environment variable stuff to the --help output?

**Comment by natemcmaster** [comment]
> What if we simply add the environment variable stuff to the --help output?

You read my mind. We started doing this recently (https://github.com/aspnet/DotNetTools/pull/218).
