### ISSUE TITLE
dotnet-watch glob pattern

### ISSUE THREAD

**Issue by mdschweda** [aspnet/DotNetTools#226]
It would make `dotnet watch` a viable tool for task runners and custom tools if you could pass a glob pattern argument instead of using the default `Project` logic.

**Comment by natemcmaster** [comment]
We've rewritten much of dotnet-watch to support MSBuild. This adds support customize what dotnet-watch watches. See [the README](https://github.com/aspnet/DotNetTools/tree/192134cad8a9805f41b94052f9d68d17f7d3afb2/src/Microsoft.DotNet.Watcher.Tools#msbuild) for details. For example, here is a custom glob in csproj:
```xml
<ItemGroup>
    <Watch Include="**\*.js" />
</ItemGroup>
```

Is this sufficient for what you are trying to accomplish?

**Comment by mdschweda** [comment]
That's great. For the time being I've created a tool called [globwatch](https://github.com/mdschweda/globwatch) that runs a custom code generation tool based on Handlebars on configuration changes. To make that work team members would need to install the .NET Core Task Runner. The solution feels a bit clumsy. If I can reproduce this setup I'm all in.

**Comment by natemcmaster** [comment]
Closing this. Not trying to be mean, but I think we have settled on the design I mentioned above. Custom watch globs can be expressed in the MSBuild project being watched.

Feel free to continue discussion. And if you have issues using expressing custom watch globs in csproj, let us know.
