### ISSUE TITLE
Add --version command-line option to tools that don't have it

### ISSUE THREAD

**Issue by cesarbs** [aspnet/DotNetTools#228]
Currently only `user-secrets` has it.

**Comment by natemcmaster** [comment]
cc @muratg 

tool | has --version flag
-----|----------
dotnet-sql-cache | added in #235
dotnet-watch | added in #235 
dotnet-user-secrets | ✅ 
dotnet-ef | ✅ 
dotnet-aspnet-codegenerator | :x:
dotnet-razor-tooling | :x:

**Comment by natemcmaster** [comment]
Fixed in https://github.com/aspnet/DotNetTools/pull/235
