### ISSUE TITLE
`dotnet user-secrets import`

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#233]
Usage

    dotnet user-secrets import [[--id userSecretId]] [-n|--no-overwrite] [OTHER_ID]

    Merges user secrets from another user secret collection.

    Arguments:
    OTHER_ID     The user secrets ID of the collection to import into the current collection.

    Options:
     -n|--no-overwrite     User secrets from OTHER_ID do not replace existing secrets with the same key.

Scenarios:
Users that want to change an the ID.
Import from another project that's already configured

Other ideas:
Same behavior can be done with `dotnet user-secrets --id OTHER_ID list --json | dotnet user-secrets set`, but is less intuitive for users, and doesn't provide a `--no-overwrite` option.

**Comment by muratg** [comment]
Closing this as we haven't heard customers asking for this.
