### ISSUE TITLE
Unsupported netcoreapp1.1 framework version

### ISSUE THREAD

**Issue by Advanium** [aspnet/DotNetTools#255]
I'm new to .NET Core so I've been watching the "Introduction to ASP.NET Core 1.0" course on MVA and followed the steps to install and use .NET Core on linux.
Unfortunately, `dotnet watch` won't work with the current version of .NET Core. As I'm trying the stack on Ubuntu 16.10, there are only 2 versions of .NET Core available today so I can't downgrade to netcoreapp1.0.

Do you have any clues on how to get this tool working anyway?

![grafik](https://cloud.githubusercontent.com/assets/515866/22081518/290116e4-ddc4-11e6-99da-e15a872e71af.png)

**Comment by natemcmaster** [comment]
What version do you have in project.json? "1.1.0-preview4-final" should support project.json and .NET Core 1.1.0

**Comment by eferhatg** [comment]
I got the same error.
<img width="870" alt="screen shot 2017-01-19 at 07 20 55" src="https://cloud.githubusercontent.com/assets/898275/22093598/0a9d08ee-de18-11e6-9271-c0371763b33a.png">

**Comment by natemcmaster** [comment]
@eferhatg you referenced "Microsoft.**AspNetCore**.Watcher.Tools". It should be "Microsoft.**DotNet**.Watcher.Tools".

```json
"tools": {
   "Microsoft.DotNet.Watcher.Tools": "1.1.0-preview4-final"
}
```

**Comment by Advanium** [comment]
@natemcmaster Thanks. That solved the issue. Where do I get an overview of the available versions for the watch tool if I had to update it later on?

**Comment by eferhatg** [comment]
Yep, this is my fault, even the error messages are not same. I guess it's the result of sleepless coding :)

It's working now. (with 1.1.0-preview4-final)
Thanks @natemcmaster .

**Comment by natemcmaster** [comment]
@Advanium as you already discovered, nuget.org is the best place to see available versions. 

I'll add one more comment though: the preview4 prereleases (both 1.0.0 and 1.1.0) are the last versions to support project.json. In the not too distant future, we will publish "1.0.0" version. This will only support MSBuild projects. If you've moved to csproj, you can try those pre-release versions of those by using '1.0.0-msbuild*' as the version.
