### ISSUE TITLE
Package 'Microsoft.Extensions.SecretManager.Tools 1.1.0-preview4-final' uses features that are not supported by the current version of NuGet.

### ISSUE THREAD

**Issue by AndyCJ** [aspnet/DotNetTools#258]
I have an ASP.Net Core project in VS2015 targeting the 4.6.1 .Net Framework.

When trying to update to 'Microsoft.Extensions.SecretManager.Tools 1.1.0-preview4-final' in the pre-releases channel I get an error message saying:

"Package 'Microsoft.Extensions.SecretManager.Tools 1.1.0-preview4-final' uses features that are not supported by the current version of NuGet."

I also get the following error showing up in the Package Manager Output: "The schema version of 'Microsoft.Extensions.SecretManager.Tools' is incompatible with version 2.12.0.815 of NuGet."

I have Nuget 3.5 installed (confirmed via Visual Studio Extension Manager and About window.

I also tried opening the "Microsoft.Extensions.SecretManager.Tools 1.1.0-preview4-final" package with the NuGet Package Explorer, which also said the scema version was incompatible.

I tried "Microsoft.Extensions.SecretManager.Tools 1.0.0-preview4" and it opened up fine.

**Comment by natemcmaster** [comment]
You probably have 3.5.0-beta2. Upgrade to the "3.5.0" RTM version. https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix (version 3.5.0.1996).

Closing. We can re-open if upgrading your tooling doesn't solve the issue.
