### ISSUE TITLE
dotnet-web

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#260]
Starts an HTTP, static-file server in the current working directory.

```
dotnet web [basedirectory] [-p|--port <PORT>] 
```

**Comment by muratg** [comment]
We'll look into this when we global tools.

**Comment by natemcmaster** [comment]
> We'll look into this when we global tools.

Consider this blocked on https://github.com/dotnet/cli/issues/5147

cc @blackdwarf

**Comment by natemcmaster** [comment]
Low demand to make an official version of this. Use https://github.com/natemcmaster/dotnet-serve instead.
