### ISSUE TITLE
Does not work with dotnet 1.1.1

### ISSUE THREAD

**Issue by ChuckkNorris** [aspnet/DotNetTools#270]
Are there plans to support this feature for ASP.NET Core 1.1.1 projects built in VS 2017?

**Comment by natemcmaster** [comment]
Can you be more specific about what doesn't work? There are multiple packages in this GitHub repo.

**Comment by ChuckkNorris** [comment]
Sorry for the vague message - I was referring to the DotNetTools watcher. The ability to run `dotnet watch run`

**Comment by natemcmaster** [comment]
Please use `1.0.0`. The 1.1.0-preview4-final version should not be used. It was a build to support project.json tools, but is not longer supported. We'll be unlisting it from NuGet so it won't appear in search results.

See https://github.com/aspnet/DotNetTools#how-to-install for instructions on how to install.

**Comment by ChuckkNorris** [comment]
Thanks for removing that from NuGet.
I tried installing `1.0.0` via nuget and received the same error.

![Error](http://image.prntscr.com/image/0ed48dd88cfb4afeb271b26b4b2c5be8.png)

Are we only able to install this via updating the csproj file?

**Comment by natemcmaster** [comment]
You must edit the csproj file directly. This is something NuGet didn't implement in VS 2017. Please use https://github.com/NuGet/Home/issues/4190 for feedback on this.

**Comment by ChuckkNorris** [comment]
Thanks for your help, @natemcmaster
