### ISSUE TITLE
Rename UserSecrets tool to UserConfig

### ISSUE THREAD

**Issue by danroth27** [aspnet/DotNetTools#277]
The User Secrets tool is useful for more than just secrets. It's nice for any configuration data that is user specific and shouldn't be shared via source control. Consider renaming it accordingly.

**Comment by natemcmaster** [comment]
I'm generally against renaming RTMed packages. NuGet doesn't support renames or redirects, which means renaming a package ID breaks upgrade scenarios.

**Comment by natemcmaster** [comment]
@muratg @glennc what are your thoughts on this? If we're gonna do rename the package, we should do it ASAP.

**Comment by muratg** [comment]
It's a product (and hence a "PM") question :trollface:.  Though if we want to go with this, I guess we can create a 2.0 version of the package with the old name as well and tell people to change their dependencies to the new name.

**Comment by muratg** [comment]
@danroth27 @DamianEdwards I don't think you'll want to rename this in 2.1 so backlogging.

**Comment by natemcmaster** [comment]
I think at this point its too late for a rename, especially now that it's bake into the SDK.
