### ISSUE TITLE
dotnet watch run with F# and suave fails to re-bind to port

### ISSUE THREAD

**Issue by mastoj** [aspnet/DotNetTools#278]
I'm trying out fable suave scaffold, https://github.com/fable-compiler/fable-suave-scaffold, which if everything works as expected has automatic reload of client and server code. The client part works as expected but when the server try to reload the server application it fails with a "Address already in use".

### Repro steps

1. Clone repo https://github.com/fable-compiler/fable-suave-scaffold
2. Start with ./build.sh run
3. Login with test/test
4. Make a change to a string in the file `Wishlist.fs`
5. You should get error message in log output on stdout

### Machine info

* OS: OSX 10.12.3

* `dotnet --info`:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

**Comment by natemcmaster** [comment]
Can you update dotnet-watch to 1.0.0 and tell me if it still reproduces? It looks like you're still using 1.0.0-msbuild2-final which was an early preview that had bugs.

https://github.com/fable-compiler/fable-suave-scaffold/blob/master/src/Server/Server.fsproj#L27

**Comment by mastoj** [comment]
Thank you @natemcmaster, it seems to work so I'm closing this.
