### ISSUE TITLE
Update package TFM for 2.0

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/DotNetTools#281]
The design for DotNetCliToolReference packages is still unclear. Not sure if we should target netcoreapp1.0 or netcoreapp2.0. At the moment, packages target netcoreapp1.0 even though the tool runs on netcoreapp2.0.

Changing the package to anything except netcoreapp1.0 causes dotnet-restore to fail. See https://github.com/NuGet/Home/issues/4396

**Comment by natemcmaster** [comment]
cc @prafullbhosale

**Comment by cesarbs** [comment]
I have an app targeting `netcoreapp2.0` and I'm seeing this error after this change:

```
C:\Users\cesars\.dotnet\x64\sdk\2.0.0-preview1-005825\NuGet.targets(97,5): error : Package Microsoft.Extensions.SecretManager.Tools 2.0.0-preview1-24645 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.SecretManager.Tools 2.0.0-preview1-24645 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [D:\src\aspnet\MetaPackages\samples\AppSettings\AppSettings.csproj]
```

**Comment by natemcmaster** [comment]
It should be resolved when https://github.com/dotnet/cli/pull/6356 is merged.
