### ISSUE TITLE
dotnet watch test block in waiting....

### ISSUE THREAD

**Issue by ShaomingCode** [aspnet/DotNetTools#283]
dotnet watch test
watch : Started
Build started, please wait...
Build completed.

Test run for D:\code\SMCore\SMCore.XUnitTest\bin\Debug\netcoreapp1.1\SMCore.XUni          tTest.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) 测试执行命令行工具版本 15.0.0.0
版权所有 (C) Microsoft Corporation。保留所有权利。

正在启动测试执行，请稍候...
[xUnit.net 00:00:00.4858050]   Discovering: SMCore.XUnitTest
[xUnit.net 00:00:00.5807001]   Discovered:  SMCore.XUnitTest
[xUnit.net 00:00:00.6205940]   Starting:    SMCore.XUnitTest
[xUnit.net 00:00:00.7324367]   Finished:    SMCore.XUnitTest

总测试: 1。已通过: 1。失败: 0。已跳过: 0。
测试运行成功。
测试执行时间: 1.3728 秒

watch : Exited
watch : Waiting for a file to change before restarting dotnet...

------------------------------------------------------------------

 dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

blocking on base

**Comment by natemcmaster** [comment]
@ShaomingCode I'm not sure I understand what problem you are seeing. Can you provide more details about what you are expecting to see versus what is happening?

**Comment by natemcmaster** [comment]
Closing as we need more details to understand the problem. We can re-open when we have those details.

See https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md#filing-issues for more details on creating a detailed bug report.
