### ISSUE TITLE
MSBuild v15 folder only contains a typescript folder and not a javascript folder also

### ISSUE THREAD

**Issue by ajberry** [aspnet/DotNetTools#295]
I have upgraded from VS2015 to VS2017 and have an issue building Cordova apps for Windows. 

I get the following error: 

    `C:\code\presales\PresalesApp\PresalesApp\platforms\windows\CordovaApp.Windows10.jsproj(61,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\JavaScript\Microsoft.VisualStudio.WJProject.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

But when I check the msbuild folder there is no JavaScript folder, only a TypeScript folder. 

I have installed all the available components under Build Tools with the Installer. What do I need to do to get the build tools to install the Javascript folder I need?

**Comment by natemcmaster** [comment]
@ajberry I'm closing this as it doesn't seem related to any of the code in this repository. This repo only contains code for a few command line tools used with ASP.NET Core apps, not Cordova apps. Try opening an issue on https://developercommunity.visualstudio.com instead. Your issue looks similar to this one: https://developercommunity.visualstudio.com/content/problem/30384/msb4019-the-imported-project-cprogram-files-x86msb.html
