### ISSUE TITLE
Add tool for creating HTTPS development certificate

### ISSUE THREAD

**Issue by danroth27** [aspnet/DotNetTools#296]
@javiercn

**Comment by javiercn** [comment]
This is done https://github.com/aspnet/DotNetTools/commit/7ac72dd7d8032074f378484e42f6ccfcc277a528

**Comment by danroth27** [comment]
This now works: `dotnet msbuild /t:GenerateSSLCertificate` for generating a development HTTPS certificate. we should probably rename the target though to not be SSL specific and to indicate the certificate is for development purposes: https://github.com/aspnet/DotNetTools/issues/301
