### ISSUE TITLE
Rename GenerateSSLCertificate target to GenerateHttpsCertificate

### ISSUE THREAD

**Issue by danroth27** [aspnet/DotNetTools#301]
SSL is a outdated protocol specific name. Also, we should make it clear that the generated certificate is for development purposes only. Suggest renaming GenerateSSLCertificate target to GenerateDevelopmentHttpsCertificate.

**Comment by danroth27** [comment]
@javiercn

**Comment by natemcmaster** [comment]
@danroth27 open to ideas that are shorter than `dotnet msbuild /t:GenerateDevelopmentHttpsCertificate`?

GenDevCert
GenerateDevCert
GenDevHttpsCert

**Comment by javiercn** [comment]
We do not abbreviate


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by natemcmaster** [comment]
Terse syntax is a worthy goal for command line tools. It's why users prefer `cd`, `ls`, and `rm` to `push-location`, `get-childitem`, and `remove-item`.

**Comment by muratg** [comment]
@danroth27 Moved this out since the rest of the feature got cut from 2.0

**Comment by danroth27** [comment]
This target was cut from 2.0
