### ISSUE TITLE
Hang in Dotnet.Watcher.Tools.FunctionalTests

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#304]
@natemcmaster thinks we might be missing a dispose in this test.

Log here: http://aspnetci/viewLog.html?tab=buildLog&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&buildId=233675#_focus=7837

**Comment by muratg** [comment]
@natemcmaster if it's straightforward, please take a look when you touch this repo next.

**Comment by natemcmaster** [comment]
I haven't seen this reproduce locally, and the link to the original failure is broken. Closing for now. Can reopen if we have more repros.
