### ISSUE TITLE
dotnet-watch should have a delay

### ISSUE THREAD

**Issue by ygoe** [aspnet/DotNetTools#305]
Currently, the application is stopped and restarted immediately when a file change is detected. This leads to multiple restarts in a short time when uploading multiple relevant files over a slow connection. You can test this yourself by watching the log output while running this command:

    touch Startup.cs; sleep 3; touch Program.cs

The delay should probably be optional and configurable.

When the application is run from source, it probably only isn't a too big issue right now because it takes 5 seconds to compile and start the application anyway. And during this time, it's just the compiler that's interrupted, not the already running application.

This is somewhat related to PHP APC's option to only cache compiled PHP files when they were last modified *n* seconds ago, because we don't want to cache a file that's only been half uploaded and doesn't compile.

**Comment by davidfowl** [comment]
Are you running applications in production with `dotnet watch`? It's a development tool only so you *really* shouldn't be doing that.

**Comment by ygoe** [comment]
I'm trying to make it as easy as possible to just upload files and have them regarded. As I've seen this is already automatically the case for View files (including Pages), but not for other code.

Is there a solution to this? Can ASP.NET (Razor Pages) be used in a similar way to other popular web scripting languages that just need 'copy deployment'? Or will deploying new files always have to include explicitly restarting the application on the server, too? Then I'd have to look at the updated files and guess whether the ASP.NET application has already noticed that or still needs a restart.

**Comment by davidfowl** [comment]
> I'm trying to make it as easy as possible to just upload files and have them regarded. As I've seen this is already automatically the case for View files (including Pages), but not for other code.

No. C# is a compiled language, trying to use it this way, you'll run into a bunch of things that go against the grain. We don't have any first class support for adding source files to your production site. Using dotnet run/watch is a hack at best and it isn't something we ever intend anyone to use outside of dev.

> Is there a solution to this? Can ASP.NET (Razor Pages) be used in a similar way to other popular web scripting languages that just need 'copy deployment'? Or will deploying new files always have to include explicitly restarting the application on the server, too? Then I'd have to look at the updated files and guess whether the ASP.NET application has already noticed that or still needs a restart.

Nope. Razor pages can't really be used like this. You still need to entire tool chain to run your razor page applications. The intent was never to make it be like php or other scripting languages. The experience will never be as smooth.

**Comment by ygoe** [comment]
Alright. Then I'll just have to consider this when deciding whether this technology is suitable for a project. I also noticed that running from a compiled DLL uses much less memory than running from full source.

If nobody else sees a point in the original issue, having a delay in the watch command, then this can be closed.

**Comment by muratg** [comment]
Closing this as by-design.
