### ISSUE TITLE
Secrets Manager 1.1.0-preview4-22752 demanding project.json to add a secret

### ISSUE THREAD

**Issue by setagana** [aspnet/DotNetTools#312]
Hi,

I'm using Secrets Manager 1.1.0-preview4-22752 and whenever I try to add a secret with  `dotnet user-secrets set MyKey MyValue` from the same directory as my csproj file, I get

`fail: The project file '{my app path}\project.json' does not exist.`

Is this a known issue with any workarounds?

**Comment by natemcmaster** [comment]
This is an unsupported version of the tool that was released before .NET Core transitioned from project.json to csproj. Use this version instead: https://www.nuget.org/packages/Microsoft.Extensions.SecretManager.Tools/1.0.1.

https://github.com/aspnet/DotNetTools/blob/dev/README.md#how-to-install
