### ISSUE TITLE
Reload browser on change

### ISSUE THREAD

**Issue by r03** [aspnet/DotNetTools#314]
I'm using 'dotnet watch run' to restart the application on a change.
Is there an option to also reload the browser after the restart?

Maybe integrate with something like [LiveReload](http://livereload.com/)?

**Comment by natemcmaster** [comment]
The best way to do this today is to use the ASP.NET Core webpack middleware. See https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services, especially the section about hot module replacement.

By the way, this enabled by default in some of our 2.0 templates. If you have 2.0.0-preview2, do the following:
```
dotnet new angular
npm install
$env:ASPNETCORE_ENVIRONMENT='Development'
dotnet watch run
```
This will start a webpack watcher that will reload the browser when your JS and HTML assets change.
