### ISSUE TITLE
No executable found matching command "dotnet-watch"

### ISSUE THREAD

**Issue by 50774283** [aspnet/DotNetTools#315]
![2](https://user-images.githubusercontent.com/16589080/27762082-bde2443c-5e9c-11e7-8175-30f5cd7f071b.PNG)
![config](https://user-images.githubusercontent.com/16589080/27762083-bde9511e-5e9c-11e7-9613-0debe9448f3d.PNG)

Same  code work fine on Windows 10 but Windows 7 do not work! How can I slove this issue? Thank you.

**Comment by BrennanConroy** [comment]
Are you sure it works on 10 and not 7? You need to add a tool reference, see https://github.com/aspnet/DotNetTools/blob/dev/samples/dotnet-watch/WatchMultipleProjects/watch.proj#L7

**Comment by natemcmaster** [comment]
+1 to what Brennan said. Your csproj is incorrect. Change it to this.
```xml
 <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0-preview2-final" />
 </ItemGroup>
```
https://github.com/aspnet/dotnettools#how-to-install

**Comment by 50774283** [comment]
@BrennanConroy @natemcmaster   Thank you.
