### ISSUE TITLE
dotnet watch crashes with StackOverflowException when watching Virtual Box shared folders

### ISSUE THREAD

**Issue by bruce31** [aspnet/DotNetTools#321]
```
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```
Microsoft Windows Version 1607 (OS Build 14393.1358)

```dotnet new xunit```
added the following to .csproj
```
<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0-preview2-final" />
</ItemGroup>
```
```dotnet test``` is successful
```dotnet watch test```  gives error box
```
[Window Title]
dotnet

[Main Instruction]
dotnet has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.
```
I did not have any issues when doing the same on Ubuntu 16.04

**Comment by natemcmaster** [comment]
@bruce31 I followed your exact steps and was unable to reproduce the issue on a clean machine. I suspect there is kind of corrupted cache on your box, or it could be a problem in the project file itself. Can you zip up and share the following file locations?

 - Your entire project folder, expecially including the `obj/` folder. 
 - `%USERPROFILE%\.nuget\packages\.tools\microsoft.dotnet.watcher.tools\`
 - Your `NuGet.config` file, if you have one.
 - `%APPDATA%\NuGet\NuGet.config`

After this, you can try resetting your entire NuGet cache by running `dotnet nuget locals all --clear`.

**Comment by bruce31** [comment]
Tried again but this time on C drive and it worked correctly.

Copied working project back to share on E: and it did not work.

Am using win10 in a virtualbox VM hosted on Mac.

E drive is 
```
E:        \\vboxsrv\Common          VirtualBox Shared Folders
```
So far watch is the only thing I am having a problem with working on E drive.

**Comment by bruce31** [comment]
Accessing the same project in the same shared host location from Ubuntu 16.04 VM works.

**Comment by natemcmaster** [comment]
Thanks, I'll try to reproduce with this setup. Can you also try one more thing?
```
dotnet -d watch --verbose test
```
This will dump more diagnostics about where the dotnet-watch loaded from and how far it got before it crashed.

**Comment by natemcmaster** [comment]
I was able to reproduce easily the same crash using a network-mounted folder. Try using the polling file watcher setting.
```
set DOTNET_USE_POLLING_FILE_WATCHER=1
dotnet -d watch --verbose test
```
See `dotnet watch --help` for more info.

**Comment by bruce31** [comment]
Works correctly using the Polling file watcher.

Thanks for your help.
