### ISSUE TITLE
Consider sorting user-secrets list result

### ISSUE THREAD

**Issue by Ketrex** [aspnet/DotNetTools#331]
I have a fairly long list of user-secrets entries for a particular project and it would be nice to see a sorted list of these items rather than having to search through the entire list to find related items. It appears items are grouped, but not sorted.

### Current `user-secrets list` output:
xyzApi:item5
xyzApi:item6
xyzApi:item3
xyzApi:item2
xyzApi:item1
xyzApi:item4

### Proposed `user-secrets list` output
xyzApi:item1
xyzApi:item2
xyzApi:item3
xyzApi:item4
xyzApi:item5
xyzApi:item6

**Comment by natemcmaster** [comment]
This seems like it should be pretty simple to implement. I would take a PR to fix it, but as it's not really a high priority, this is going on the backlog for now.

In the meantime, you can always pipe output to `sort` if you're using powershell or bash.
```
dotnet user-secrets list | sort
```

**Comment by natemcmaster** [comment]
I'm closing as we have no plans to implement this ourselves. We would still accept a PR for this. If you want to implement this feature, send a PR.
