### ISSUE TITLE
Support for .NETStandard1.6+ and .NETCoreApp1.1 ?

### ISSUE THREAD

**Issue by darkguy2008** [aspnet/DotNetTools#335]
Hey!

I have a project in which I need to use .NET Standard 1.6 (for ImageSharp) and .NET Core App 1.1. However, if I add .NETStd I lose support for DotNetTools (specifically the watcher). This is what I get when I run ```dotnet restore```:

```/usr/local/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): error : Package Microsoft.DotNet.Watcher.Tools 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Watcher.Tools 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [/Users/user/_git/project/project.csproj]```

I found out that if I manually run the project this way, it works:

```dotnet build -f netcoreapp1.1 && dotnet run -f netcoreapp1.1```

So, is there a way to make the watcher do this automatically instead? Any alternatives or support for this behavior is planned?

Thanks!

**Comment by natemcmaster** [comment]
> /usr/local/share/dotnet/sdk/1.0.4/NuGet.targets

It appears you are using the .NET Core 1.0.4 SDK with dotnet-watch 2.0.0. dotnet-watch 2.0.0 requires the .NET Core 2.0.0 SDK. You should try one of these options:

  - Upgrade to the .NET Core 2.0.0 SDK. (https://www.microsoft.com/net/download/core) FYI upgrading to the 2.0.0 SDK will still allow you to build and run .NET Core 1.1/.NET Standard 1.6.
 - Use Microsoft.DotNet.Watcher.Tools version 1.0.1 instead.
