### ISSUE TITLE
dotnet-watch - Docs sample out-of-date?

### ISSUE THREAD

**Issue by snerks** [aspnet/DotNetTools#342]
Apologies if there is a newer version of this sample (it appears to have been published in March 2017)...

According to the tutorial "Developing ASP.NET Core apps using dotnet watch":
https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch

The version to add is given as `1.0.0`:
```xml
<ItemGroup>
 <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0" />
</ItemGroup> 
```

Perhaps this should now be updated to `2.0.0`, which has, for example, better colourisation.

**Comment by natemcmaster** [comment]
I'd happily take a PR to update samples.

**Comment by snerks** [comment]
Looks like @vanillajonathan has updated it already. Thanks!
