### ISSUE TITLE
Fix ApiCheckGenerate

### ISSUE THREAD

**Issue by javiercn** [aspnet/DotNetTools#346]
* Port to 2.0
* Add a solution target for it so that people can run build.cmd /t:GenerateApiCheckBaselines
* Make sure that it runs and doesn't throw exceptions
* Make it depend on Compile so that you ensure assemblies are there.

**Comment by javiercn** [comment]
@ryanbrandenburg

**Comment by natemcmaster** [comment]
Did you mean to open this on BuildTools?

**Comment by javiercn** [comment]
@natemcmaster Yes. My brain is not working
