### ISSUE TITLE
Secrets Manager - 15.5 Preview Compatibility 

### ISSUE THREAD

**Issue by jsheetzati** [aspnet/DotNetTools#350]
Is the Secrets Manager compatible with the 15.5 Preview?  I no longer see "Manage User Secrets" when right-clicking on my project.

**Comment by natemcmaster** [comment]
@mlorbetske any ideas?

**Comment by mlorbetske** [comment]
@BillHiebert this has been fixed for 15.5 preview 2, right?

**Comment by BillHiebert** [comment]
Yes

**Comment by natemcmaster** [comment]
Sounds like this is a known issue in VS. Closing as it will be fixed when 15.5 preview 2 is available.

Until then, you can use `dotnet user-secrets` on command line to manage your secrets.

**Comment by jsheetzati** [comment]
Thanks guys.
