### ISSUE TITLE
dotnet watch Does not run webpack

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/DotNetTools#352]
I'm using `dotnet watch run` on my Vue.js SPA project I built using the ASP.NET Core SPA templates. I added TS-Lint support to webpack via the `tslint-loader`. My csproj contains the following code (default to the SPA template) that runs webpack before a build:

```
<Target Name="DebugRunWebpack" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />

    <!-- In development, the dist files won't exist on the first run or when cloning to
         a different machine, so rebuild them if not already present. -->
    <Message Importance="high" Text="Performing first-run Webpack build..." />
    <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js" />
    <Exec Command="node node_modules/webpack/bin/webpack.js" />
  </Target>
```

Using `dotnet watch run` does not seem to cause the above scripts to execute. In theory, when a file changes, it should perform a build of the project which should cause the above code to execute but it doesn't. Is there any way to achieve this?

**Comment by natemcmaster** [comment]
dotnet-watch doesn't do anything special to change your build targets. Does `dotnet run` invoke your DebugRunWebpack target? Bear in mind that dotnet run first executed `dotnet build` but suppresses all console output.

cc @SteveSandersonMS - spa templates

**Comment by RehanSaeed** [comment]
That must be it then, I looked at `dotnet run --help` but there doesn't seem to be a way to stop it supressing console output. Perhaps I should move this issue to the dotnet cli repository.

**Comment by natemcmaster** [comment]
Yup, dotnet/cli is the right place for this request. Closing as this is external to dotnet-watch.

**Comment by RehanSaeed** [comment]
Moved to https://github.com/dotnet/cli/issues/7932
