### ISSUE TITLE
Exiting with Error code 1

### ISSUE THREAD

**Issue by JonyTek** [aspnet/DotNetTools#359]
I am running a Dotnet Core 2.0 Web Api application and I am having issues when running dotnet watch run.

I have manually added the package to the .csproj file of the main Api project.

`<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>`

When I run the command in the console I see the below. Any Ideas?

C:\Working\boom-repository\boom-web-api\Boom.Api>dotnet watch run
watch : Started
watch : Exited with error code 1
watch : File changed: C:\Working\boom-repository\boom-web-api\Boom.Api\Controllers\AccountController.cs
watch : Started
watch : Exited with error code 1
watch : File changed: C:\Working\boom-repository\boom-web-api\Users\Boom.Users.Core\Services\AccountEmailConfirmationService.cs

Unhandled Exception: System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.Internal.CommunicationsUtilities.WriteLongForHandshake(PipeStream stream, Int64 value)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
watch : Started
watch : Exited with error code 1
watch : File changed: C:\Working\boom-repository\boom-web-api\Users\Boom.Users.Core\Services\AccountEmailConfirmationService.cs
watch : Started

**Comment by JonyTek** [comment]
So with a little bit more investigating and understanding of the process the watch is working as expected although I still see the error code 1.

**Comment by natemcmaster** [comment]
Try `dotnet watch --verbose run` to give you more detail about what's happening under the hood.

**Comment by JonyTek** [comment]
This was a misunderstanding of the work flow so have closed the issue.
