### ISSUE TITLE
watch: Exited with error code -1073741510

### ISSUE THREAD

**Issue by mustafaodeh123** [aspnet/DotNetTools#362]
Hi,
What is this issue about and how to solve it?
![image](https://user-images.githubusercontent.com/12648719/33073354-ab390f5a-ce90-11e7-945b-14b5dda6aafa.png)

**Comment by natemcmaster** [comment]
This happens when you press Ctrl+C to exit a process. When you force kill a process like this, it returns a non-zero exit code.
