### ISSUE TITLE
watch: doesn't work and makes webpack watch not work - Ubuntu 17.10

### ISSUE THREAD

**Issue by cerniusnet** [aspnet/DotNetTools#363]
I have recently upgraded to Ubuntu 17.10 and _dotnet watch run_ doesnt work as intended on my project anymore. It doesn't build my .net sources on change, and also makes webpack watch not work (webpack watch works as intended if I run the project with _dotnet run_).

**Comment by natemcmaster** [comment]
Can you provide steps to reproduce this problem?

**Comment by cerniusnet** [comment]
The issue is on my side somehow, it works as intended for newly generated projects. The issue can be closed. 

But if you could, maybe you could help me understand:
I've tried every possible thing to do and in the end I set the DOTNET_USE_POLLING_FILE_WATCHER to be 1, and it started working. Could you elaborate how polling file watcher is different from CoreFX one?

**Comment by natemcmaster** [comment]
The polling file watcher keeps a snapshot of LastWriteTime for all watched files. Every 500ms, it re-scans all files to see if LastWriteTime has changed.

The BCL file watcher uses native filesystem APIs to trigger events when files change. These triggers may not exist in some file drivers, like network shares and Docker host-mounted volumes.
