### ISSUE TITLE
Flaky test: FileInSubdirectory

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#369]
An example [here](http://aspnetci/viewLog.html?buildId=364751&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe).

This is possibly related to dotnet/corefx#23473?

**Comment by natemcmaster** [comment]
dotnet/corefx#23473 was fixed in October. We should have a runtime with this improvement. Have we seen this recently?

**Comment by ryanbrandenburg** [comment]
We haven't had any reproductions in the last 30 days, will re-open if we do.
