### ISSUE TITLE
Problem installing tool watch

### ISSUE THREAD

**Issue by snovak7** [aspnet/DotNetTools#375]
On Mac, I cannot install as described with "dotnet install tool watch"

`No executable found matching command "dotnet-install"`

I use latest SDK version 2.1.3 "dotnet --version"

`2.1.3`

**Comment by rahulsalvi2k7** [comment]
Same on windows 10.

**Comment by rahulsalvi2k7** [comment]
Here is how I fixed it:
1. Add below code in your .csproj file:
`<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.Dotnet.Watcher.Tools" Version="2.0.0" />
  </ItemGroup>
`
2.Save .csproj file
3. From terminal run "dotnet restore" command

**Comment by natemcmaster** [comment]
The instructions in the dev branch require a nightly build of the dotnet core SDK, which you can get here: https://github.com/dotnet/cli.

The instructions for RTM versions of dotnet-watch are here. https://github.com/aspnet/DotNetTools/tree/release/2.0.0#how-to-install.  I'll update the README to indicate the instructions only apply to prerelease bits for now.

**Comment by keatz55** [comment]
@natemcmaster Thanks for the info, but the url, https://github.com/aspnet/DotNetTools/tree/release/2.0.0#how-to-install returns a 404 not found.

**Comment by natemcmaster** [comment]
We renamed that branch. It's here now https://github.com/aspnet/DotNetTools/tree/release/2.0#how-to-install

**Comment by keatz55** [comment]
@natemcmaster Thanks!
