### ISSUE TITLE
Include error messages in test failures

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#376]
When some of the functional tests for dotnet-watch fail we get unhelpful exceptions like [this](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=382588&_focus=13877). Let's write out the Error output of the process to make them easier to debug.

**Comment by natemcmaster** [comment]
The tests forward all stderr/stdout to ITestOutputHelper. Does the TRX file or test results contain the captured output?

**Comment by ryanbrandenburg** [comment]
You're correct, the info was there, I'm just blind.
