### ISSUE TITLE
Files shown twice in VS for Mac with dotnet watch config

### ISSUE THREAD

**Issue by c17r** [aspnet/DotNetTools#389]
I'll start with I realize this is probably not your fault but I figured I'd get a quicker from you before moving up the chain.  I'm working with a project that has the angular front end in the project via `dotnet new angular`  I added in the watcher as:
```
<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
    <Watch Include="**\*.cs" />
</ItemGroup>
```
Because without the `Watch` it was triggering for changes in TS, LESS, etc files.

If I open the solution in Visual Studio for Mac, all the CS files are shown duplicated in the tree:
![screen shot 2018-02-01 at 6 34 10 pm](https://user-images.githubusercontent.com/148640/35708970-98d57296-077e-11e8-950e-86e82770dd03.png)

If I unload the project, remove the `Watch` line, and reload the project everything comes up fine:
![screen shot 2018-02-01 at 6 35 57 pm](https://user-images.githubusercontent.com/148640/35709058-e7bb5ad8-077e-11e8-85cc-7ed8c9866ea3.png)

Is there anything in the Watcher that could be causing this?  I'm going to ask the VS for Mac team but I figured I'd ask here for to nip any finger pointing.

Thanks.

**Comment by natemcmaster** [comment]
Try this:
```
<Watch Include="**\*.cs" Visible="false" />
```

**Comment by c17r** [comment]
That seems to have done the trick, thanks!
