### ISSUE TITLE
macOS - No executable found matching command “dotnet-watch”

### ISSUE THREAD

**Issue by node-gs** [aspnet/DotNetTools#398]
I am using the dotnet cli with macOS Sierra 10.12.6

I have typed this command:

`dotnet new web`

`dotnet run`

So far so good.

When I have change: 

    app.Run(async (context) =>
                {
                    await context.Response.WriteAsync("Hello World");
                });
as per: [https://www.youtube.com/watch?v=aIkpVzqLuhA][1]
and refresh the browser, nothing happens. I thought that this might need the watch package, so typed:

`dotnet add package Microsoft.DotNet.Watcher.Tools --version 2.0.0`

Which installs successfully; csproj contains:
 

     <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
        <PackageReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
      </ItemGroup>

when I try to run `dotnet watch` or `dotnet watch run`, I get the error: 

`No executable found matching command "dotnet-watch"`

  [1]: https://www.youtube.com/watch?v=aIkpVzqLuhA

**Comment by natemcmaster** [comment]
You need to use DotNetCliToolReference, not PackageReference. See https://github.com/aspnet/DotNetTools/blob/release/2.0/README.md#how-to-install for instructions on how to install.

**Comment by ojemuyiwa** [comment]
Hi @natemcmaster can you please elaborate as the link you provided looks good, but lacks information as to how to actually resolve the issue / install properly so that dotnet watch actually runs
