### ISSUE TITLE
Remove Microsoft.NETCore.Platforms package in nuspec of tools

### ISSUE THREAD

**Issue by wli3** [aspnet/DotNetTools#400]
No need to add `Microsoft.NETCore.Platforms` package to nspec anymore

https://github.com/dotnet/cli/issues/8617

Reference https://github.com/dotnet/cli/issues/8418

**Comment by wli3** [comment]
@natemcmaster

**Comment by natemcmaster** [comment]
Awesome, thanks @wli3.

cc @prafullbhosale for scaffolding.
