### ISSUE TITLE
Have dotnet-user-secrets generate an ID and add it to the project file when attempting to user it and there is no existing ID

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/DotNetTools#402]
Today, if you attempt to use `dotnet user-secrets` on a project that doesn't have `UserSecretsId` property set, it returns an error. Perhaps we should instead generate a new ID (projectname + guid?) and add it to the project file automatically. Or maybe we should facilitate that in a new sub-command (e.g. `dotnet user-secrets init`), rather than doing it implicitly on failure.

Thoughts? @natemcmaster @davidfowl @glennc @danroth27

**Comment by natemcmaster** [comment]
Looks like a duplicate of #166

**Comment by DamianEdwards** [comment]
Doh
