### ISSUE TITLE
Using dotnet watch from launchsettings.json no longer works

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/DotNetTools#404]
I used to be able to use `dotnet watch` in Visual Studio by adding the following section to `launchSettings.json` and starting the project without debugging using CTRL + F5.

```
    "Kestrel (dotnet watch run)": {
      "commandName": "Executable",
      "executablePath": "C:\\Program Files\\dotnet\\dotnet.exe",
      "commandLineArgs": "watch run",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
```

This used to work in ASP.NET Core 1.1 but no longer does. The commandName is a new required property that seems to have been added in 2.0 that I have added. I have tried values of `Project` and `Executable` but the project no longer starts. Please can you bring this back as a supported scenario.

**Comment by natemcmaster** [comment]
Is dotnet watch working correctly when launching it from the command line? If so, this sounds like a Visual Studio bug.

**Comment by RehanSaeed** [comment]
`dotnet watch run` works perfectly in PowerShell. When I use `"commandName": "Executable"`, I see a command window pop up and instantly disappear.

**Comment by natemcmaster** [comment]
My guess is that you need to set workingDirectory. The default working directory will be the build output folder (bin/Debug/netcoreapp2.0/) not the project directory. This worked for me:
```
    "Kestrel (dotnet watch run)": {
      "commandName": "Executable",
      "executablePath": "C:\\Users\\namc\\.dotnet\\x64\\dotnet.exe",
      "commandLineArgs": "watch run",
      "workingDirectory": "C:\\Users\\namc\\source\\repos\\WebApplication2\\WebApplication2",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

**Comment by RehanSaeed** [comment]
Is there a way to make the working directory more generic? Having to hard code a path in there is sub-optimal. Also, is there some documentation for launchSettings.json somewhere?

**Comment by RehanSaeed** [comment]
I've also heard that `launchSettings.json will now be used in VS Code too, so can we also somehow make `executablePath` generic, so I don't have to hard code a Windows only path `C:\\Program Files\\dotnet\\dotnet.exe`.

**Comment by natemcmaster** [comment]
@RehanSaeed sorry, I can't help with that. These would be a Visual Studio/VS Code features...not something we can implement in dotnet-watch.

**Comment by RehanSaeed** [comment]
Raised https://github.com/aspnet/Tooling/issues/1067, I suppose this can be closed.
