### ISSUE TITLE
Flattened user-secrets not compatible with Visual Studio for Windows Secrets Manager.

### ISSUE THREAD

**Issue by rcollette** [aspnet/DotNetTools#405]
If secrets with nested keys are created in Visual Studio for Windows secrets manager, the following code works just fine.
```
            var signingKeys = Configuration.GetSection("Tokens:AuthToken:SigningKeys");
            foreach (var key in signingKeys.GetChildren())
            {
                issuerSigningKeys.Add(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key.Value)));
            }
```
However, a design decision was made to not support nested secrets in the cli tool.  I wind up having 
to hand create the secrets.json file, and its containing folder.

```
{
    "Tokens": {
        "AuthToken": {
            "SigningKeys": {
                "SigningKey1": "",
                "SigningKey2": ""
            }
        }
    }
}
```
How is it that there is some disconnect between what Visual Studio Windows does and what the CLI does.  I'm on a mac so I have to use the CLI tool

I know there was also discussion about discouraging hand editing the file, but that is exactly what I am having to do because of this disconnect.

**Comment by natemcmaster** [comment]
> How is it that there is some disconnect between what Visual Studio Windows does and what the CLI does.

We had other work we considered more important. Fortunately, improvements to this are coming soon. :) https://github.com/aspnet/DotNetTools/tree/dev/tooling/Microsoft.VisualStudio.SecretManager

**Comment by natemcmaster** [comment]
Closing as the code for secret manager and VS is moving to @vijayrkn's team, and the code is moving into Visual Studio. My team won't be addressing this before the ownership of the code moves. https://developercommunity.visualstudio.com is the best place to submit feedback and feature requests for VS functionality.
