### ISSUE TITLE
File Access Error on watch run

### ISSUE THREAD

**Issue by livarcocc** [aspnet/DotNetTools#406]
_From @jdenekat on March 12, 2018 23:31_

## Steps to reproduce
Checkout a project that uses "watch" on a new computer, type "dotnet watch run"

## Expected  behavior
It should build and run

## Actual behavior
The first thing it does is try to populate a local package cache at the same time it watches, leading to a file contention error.

Work-around:

First, just do "dotnet run".  It will build the local package cache.  Afterwards you can use "dotnet watch run" without file contention.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

_Copied from original issue: dotnet/cli#8773_

**Comment by natemcmaster** [comment]
Hmm, this one is tricky. Not sure there is a good way for dotnet-watch to solve it. You can use this environment variable, however, to disable first-run package cache population.
```ps1
$env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE='true'
```

@livarcocc @wli3 will first run experience run for bundled SDK tools in 2.1.300? It appears they may be skipped for DotNetCliToolReference's.

**Comment by livarcocc** [comment]
They should run for bundled SDK tools, as the fact they are bundled tools is just an implementation detail. From the user's perspective, they are native commands. If that's not happening, I would say that's a bug in the CLI and we should fix it.

@wli3 can you double check?

**Comment by wli3** [comment]
In a clean VM, the first run is triggered .

![image](https://user-images.githubusercontent.com/6993335/37362758-4ff4b81c-26b3-11e8-9ac9-0a2eff98a052.png)

**Comment by natemcmaster** [comment]
What about for tools installed via DotNetCliToolReference or dotnet-install-tool (and resolved via PATH)?

**Comment by wli3** [comment]
`DotNetCliToolReference` in theory it should, however, it is not a valid scenario, you need `dotnet restore` to pull these tools down and `dotnet restore` has triggered it already.

installed tool will not in theory, but, again, you need `dotnet install` first, so it would be triggered by the time tools get invoked.

**Comment by natemcmaster** [comment]
That's a good point. @jdenekat how are you installing dotnet-watch? It seems like the first-run package cache should have run before `dotnet watch` begins execution

**Comment by natemcmaster** [comment]
Closing due to lack of response. As mentioned above, use `$env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE='true'` to disable the package cache initialization.
