### ISSUE TITLE
dotnet global tools fail to install on various Linux distros (2.1.0-preview1-final)

### ISSUE THREAD

**Issue by ciddan** [aspnet/DotNetTools#408]
I'm unable to install dotnet global tools on Korora (Fedora 26 variant) and Solus due to my target framework being "unsupported". On Solus I've installed dotnet using the generic linux-64 .tar-gz download.

The error message is as follows:
```
Install failed. Failed to download package:
NuGet returned:

Failed to restore package. 
WorkingDirectory: 
Arguments: restore /tmp/ijtjy1ai.ycp/nyfhrzwu.rdb.csproj --runtime solus.3.99-x64 /p:BaseIntermediateOutputPath=\"/home/cid/.dotnet/toolspkgs/dotnet-user-secrets/2.1.0-preview1-final\"
Output:   Restoring packages for /tmp/ijtjy1ai.ycp/nyfhrzwu.rdb.csproj...
/tmp/ijtjy1ai.ycp/nyfhrzwu.rdb.csproj : error NU1202: Package dotnet-user-secrets 2.1.0-preview1-final is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / solus.3.99-x64. Package dotnet-user-secrets 2.1.0-preview1-final does not support any target frameworks.
  Restore failed in 116.28 ms for /tmp/ijtjy1ai.ycp/nyfhrzwu.rdb.csproj.
```

The problem seems to be this bit: **netcoreapp2.1 (.NETCoreApp,Version=v2.1) / solus.3.99-x64**. Can I somehow configure my system to report as the generic linux-x64 instead?

**Comment by ciddan** [comment]
Manually running the dotnet restore command I can get NuGet to restore the packages, but the CLI still doesn't know about them.

```
$ dotnet restore /tmp/lfpejjke.l53/wulvjo53.ipx.csproj --runtime linux-x64 /p:BaseIntermediateOutputPath=\"/home/cid/.dotnet/toolspkgs/dotnet-watch/2.1.0-preview1-final\"
  Restoring packages for /tmp/lfpejjke.l53/wulvjo53.ipx.csproj...
  Restore completed in 93.33 ms for /tmp/lfpejjke.l53/wulvjo53.ipx.csproj.

$ dotnet watch run
No executable found matching command "dotnet-watch"
```

**Comment by natemcmaster** [comment]
@ciddan unfortunately, this is one of the limitations of the current design of dotnet-install-tool. This isn't something dotnet-user-secrets can workaround because the runtime identifier for solus.3.99-x64 and Korora do not show up in the RID graph as defined in [Microsoft.NETCore.Platforms](https://github.com/dotnet/corefx/tree/master/pkg/Microsoft.NETCore.Platforms).

@nkolev92 @wli3 @livarcocc @peterhuene - have there been any improvements or changes to RID restore on dotnet-install-tool in preview2?

**Comment by peterhuene** [comment]
Will did some work for packing and restoring using a RID of `Any`, thus removing the reference to `Microsoft.NETCore.Platforms`.

**Comment by natemcmaster** [comment]
Ok thanks, Peter. 

@ciddan this means you're out of luck for preview1. Sorry. I don't know of any workarounds for this one.

Closing as this should be fixed in preview2.

**Comment by ciddan** [comment]
@natemcmaster Fair enough. Will wait for preview2, then. Thanks for taking a look.
