### ISSUE TITLE
Flaky tests: CreatingWritingDeletingCreatingFileWillReload et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#412]
_From @ryanbrandenburg on March 12, 2018 19:12_

These tests have recently taken to failing on OSx: http://aspnetci/project.html?projectId=XPlat&buildTypeId=XPlat_Mac_MacUniverseCoreCLR&tab=testDetails&testNameId=3759396832575739260&order=START_DATE_DESC&branch_XPlat=__all_branches__&itemsCount=50

Offending tests include:
 * FileWatcherTests.MultipleFiles(usePolling: False)
 * ConfigurationTests.CreatingWritingDeletingCreatingFileWillReload
 * ConfigurationTests.TouchingFileWillReload 

```
Assert.Equal() Failure
                   ↓ (pos 9)
Expected: JsonValue2
Actual:   JsonValue1
                   ↑ (pos 9)
   at Microsoft.Extensions.Configuration.Test.ConfigurationTests.<TouchingFileWillReload>d__32.MoveNext() in /_/test/Config.FunctionalTests/ConfigurationTests.cs:line 598
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

_Copied from original issue: aspnet/Configuration#795_

**Comment by ryanbrandenburg** [comment]
A non-exhaustive list of the builds affected by this can be found [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:ConfigJson,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by ryanbrandenburg** [comment]
_From @HaoK on March 12, 2018 19:50_

So the config tests will definitely fail if the file watcher functional tests are faling too:

https://github.com/aspnet/DotNetTools/blob/261b27b70027871143540af10a5cba57ce07ff97/test/dotnet-watch.FunctionalTests/FileWatcherTests.cs

**Comment by natemcmaster** [comment]
Why was this moved to this repo?

**Comment by natemcmaster** [comment]
Which file watcher are you talking about? We have two:

https://github.com/aspnet/FileSystem/blob/dev/src/FS.Physical/PhysicalFilesWatcher.cs
https://github.com/aspnet/DotNetTools/blob/dev/src/dotnet-watch/Internal/FileWatcher.cs

Unless the flaky tests is using dotnet-watch, then the issue actually belongs to the filewatcher in FileSystem.

**Comment by ryanbrandenburg** [comment]
Ahh, didn't realize we had the PhysicalFilesWatcher too. But it does seem like both are suffering from the same issue. I'll open against FileSystem and edit this issue to omit FS related stuff.

**Comment by mikeharder** [comment]
These 3 tests only failed on a single mac agent (aspnet-mac-a02) between Feb 26 2018 and Mar 19 2018:

http://aspnetci/project.html?tab=testDetails&testNameId=3759396832575739260&projectId=AspNetEf&order=TEST_STATUS_DESC
http://aspnetci/project.html?projectId=AspNetEf&buildTypeId=&tab=testDetails&testNameId=-154609079691610120&order=TEST_STATUS_DESC&branch_AspNetEf=__all_branches__&itemsCount=50
http://aspnetci/project.html?projectId=AspNetEf&buildTypeId=&tab=testDetails&testNameId=3801040294342729521&order=TEST_STATUS_DESC&branch_AspNetEf=__all_branches__&itemsCount=50

Since there have been no failures since Mar 19 2019, I suspect this was a temporary issue limited to one agent.  Closing until this repros again.
