### ISSUE TITLE
Ability to leak secrets store data?

### ISSUE THREAD

**Issue by niemyjski** [aspnet/DotNetTools#413]
I saw a link posted to https://github.com/aspnet/DotNetTools/blob/dev/src/dotnet-user-secrets/Internal/SecretsStore.cs in slack and looking at it... I wondered if this class should be marked with a NonSerializedAttribute to help prevent someone from serializing/leaking all the secrets (as part of a log message or the like...) or this should be using DP api's? For example, someone could submit a pr and call this tool and leak all the secrets as part of the build server.

**Comment by natemcmaster** [comment]
This type is only meant for the command line utility and should not be used as API surface. Was someone compiling against this API and calling into it directly?

**Comment by Eilon** [comment]
Tagging @blowdart .

I don't believe there's any concern here - anyone with access to run code on a machine can read the secrets stored there. There's no particular trust required for this - you just need to be able to run code.

**Comment by blowdart** [comment]
And it's not like we expect or even want you to use this on a build server, it's a developer time/developer machine scenario.

**Comment by niemyjski** [comment]
That's great and all, but people will use it everywhere esp with global tools :) I'll close this issue, just wanted to bring this issue up.
