### ISSUE TITLE
Can't Install Microsoft.DotNet.Watcher.Tools

### ISSUE THREAD

**Issue by DanJ210** [aspnet/DotNetTools#414]
I've got a standard DotNetCore 2.0 MVC web app and I'm not sure why I'm getting the error below. Everywhere else seems to be able to add this just fine. Any ideas what I'm doing wrong? Using VS 2017 which is great with packages.

![dotnetwatchererror](https://user-images.githubusercontent.com/16159685/38037276-85f33d48-3276-11e8-8644-10211ee8070e.PNG)

**Comment by natemcmaster** [comment]
Does this help? https://github.com/aspnet/DotNetTools/blob/rel/2.0.0/README.md#how-to-install

**Comment by DanJ210** [comment]
Unfortunately not but thanks for the suggestion so far. I almost thought it was going to for a second. I get these errors whether I do them in VS Code (SS) or Visual Studio 2017. Never seen anything like it before. I chose the latest version but I think as long as it starts with 2 then the rest shouldn't matter.

Oh and the error in Startup isn't an error, you can see it as a red file in solution explorer, I fixed it in VS 2017 but Code still detects it as an error for some reason. Runs without error. Only errors I get are from these packages ;(

![dotnetwatchererror2](https://user-images.githubusercontent.com/16159685/38052190-68062c3c-329e-11e8-84a3-2cc3502176be.PNG)

**Comment by natemcmaster** [comment]
I see the issue now. Change this line
```
<PackageReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.1" />
```
to this
```
<DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.1" />
```

**Comment by DanJ210** [comment]
I think I was doing it right the first time because I was getting from docs. I was using a NuGet package installer with VSCode which doesn't look like it likes CLI references. But still getting the error. What's weird is that VS 2017 should know the correct way and even it was throwing the same errors.

![dotnetwatchererror3](https://user-images.githubusercontent.com/16159685/38052591-c175dae6-329f-11e8-93d7-48ed355f2ef4.PNG)

**Comment by natemcmaster** [comment]
You also need to change Microsoft.Extensions.Caching.SqlConfig.Tools and Microsoft.Extensions.SecretManager.Tools to be DotNetCliToolReference

**Comment by DanJ210** [comment]
Oh ok, I should've known. I've never added CLI tools before. But I did copy the DotNet.Watcher.Tools from code which did have the CLI reference. So Idk what's up with that exactly unless I really made a mistake but I'm looking at the line I copied so idk.

That fixed it. Thanks very much for your help.

**Comment by natemcmaster** [comment]
Happy to help.
