### ISSUE TITLE
Make DOTNET_RUNNING_IN_CONTAINER imply DOTNET_USE_POLLING_FILE_WATCHER

### ISSUE THREAD

**Issue by richlander** [aspnet/DotNetTools#415]
For dotnet watch

See https://github.com/dotnet/dotnet-docker/issues/432

**Comment by natemcmaster** [comment]
FYI https://github.com/aspnet/DotNetTools/issues/416 gives me pause on this. We may need to do more work on the polling watcher first before we default everyone into this with no good opt-out.

**Comment by natemcmaster** [comment]
Closing because we do not currently have plans to make this change.
