### ISSUE TITLE
DotNetTools under github.com/dotnet?

### ISSUE THREAD

**Issue by kasper3** [aspnet/DotNetTools#428]
There are some official tools present in this repo and then some dotnet repos have tools scattering around like sgen (dotnet/corefx#25138), then some missing tools that people are requesting (resgen, xsd).

Would it make sense to move this repo under Github.com/dotnet, next to dotnet/cli repo so all the official tools related requests land in one place? Alternatively, create anther repo under dotnet org with same name?

@natemcmaster, @weshaggard, @KathleenDollard, @livarcocc

**Comment by Eilon** [comment]
The tools in this repo are closely part of ASP.NET Core and EF Core, so moving them to the dotnet org would be confusing for most people interested in those tools. I think for people interested in tools such as resgen and xsd, I doubt they would come to this repo looking for information. But, even if so, perhaps we can just add info to the README of this repo?

**Comment by natemcmaster** [comment]
The README in this repo already lists the tools here. I believe it's sufficiently clear already, but feel free to propose changes if its not.

There are other subcommands of `dotnet` that don't live under https://github.com/dotnet. vstest, msbuild, nuget. I think a better solution than moving all repos to the same GitHub org is to document where subcommands in https://github.com/dotnet/cli. I started doing that already, but it's probably not visible enough. https://github.com/dotnet/cli/blob/master/Documentation/general/aspnetcore-tools.md
