### ISSUE TITLE
dotnet user-secrets fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by richlander** [aspnet/DotNetTools#440]
I was expecting the following command to succeed. It does not.

```console
rich@rich-Virtual-Machine:~/dotnet-docker/samples/aspnetapp$ dotnet --version
2.1.300-rc1-008673
rich@rich-Virtual-Machine:~/dotnet-docker/samples/aspnetapp$ dotnet user-secrets -p aspnetapp/aspnetapp.csproj set "Kestrel:Certificates:Development:Password" "crypticpassword"
System.UnauthorizedAccessException: Access to the path '/home/rich/.microsoft/usersecrets/31051026529000467138' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.SecretManager.Tools.Internal.SecretsStore..ctor(String userSecretsId, IReporter reporter)
   at Microsoft.Extensions.SecretManager.Tools.Program.RunInternal(String[] args)
   at Microsoft.Extensions.SecretManager.Tools.Program.TryRun(String[] args, Int32& returnCode)
Command failed : Access to the path '/home/rich/.microsoft/usersecrets/31051026529000467138' is denied.
rich@rich-Virtual-Machine:~/dotnet-docker/samples/aspnetapp$ ls /home/rich/.microsoft
UserSecrets
rich@rich-Virtual-Machine:~/dotnet-docker/samples/aspnetapp$ ls /home/rich/.microsoft/UserSecrets/
```

**Comment by javiercn** [comment]
@natemcmaster putting this on your radar

**Comment by natemcmaster** [comment]
Hmm, linux file systems are typically case sensitive. `usersecrets` != `UserSecrets`. What are the permissions on parent folder? `ls -al /home/rich/.microsoft`

**Comment by natemcmaster** [comment]
also, is this a mounted volume in your VM? (rich-Virtual-Machine)

**Comment by natemcmaster** [comment]
I was just trying to suggest one way this folder may have been created with root permissions without you knowing about it. The same would happened if you ran `sudo dotnet user-secrets`. Regardless, the folder is owned by root. The error is accurate - `rich` does not have permissions to use this folder

**Comment by richlander** [comment]
I'm not looking for help on this issue. I worked around it for what I was trying to do. I'm instead reporting that maybe the tool isn't doing the right thing. I don't know how I got into this state, but I'm guessing others will as well. So, this is purely a product report for your consideration.

**Comment by natemcmaster** [comment]
Ok. If you can provide exact repro steps on a clean machine, we can investigate more. Without those, I can't help. This appears to be bad machine state. As I said before, you may have got there by using VMs shared folders, Docker containers, or running tools as sudo.

**Comment by natemcmaster** [comment]
Closing as this isn't something we've been able to repro. I'm happy to look into it more if you can help us identify what is creating the `/home/rich/.microsoft` folder as `root:root`.
