### ISSUE TITLE
dotnet watch run not interactive for ASP.NET Core apps

### ISSUE THREAD

**Issue by richlander** [aspnet/DotNetTools#442]
`dotnet watch run` does not provide any feedback that the app has been re-compiled for ASP.NET Core apps. It does for console apps. I believe that this is a regression.

I see similar behavior when using Docker with `microsoft/dotnet-nightly:2.1-sdk`

It is also doing something weird on Windows after I hit CTRL-C with the last error printed from `dotnet watch`.

```console
C:\git\dotnet-docker\samples\aspnetapp\aspnetapp>dotnet --version
2.1.300-rc1-008673
C:\git\dotnet-docker\samples\aspnetapp\aspnetapp>dotnet watch run
watch : Started
Hosting environment: Production
Content root path: C:\git\dotnet-docker\samples\aspnetapp\aspnetapp
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
Application is shutting down...
watch : Shutdown requested. Press Ctrl+C again to force exit.
^C
C:\git\dotnet-docker\samples\aspnetapp\aspnetapp>watch : Exited with error code -1073741510
```

**Comment by natemcmaster** [comment]
> dotnet watch run does not provide any feedback that the app has been re-compiled for ASP.NET Core apps. It does for console apps.

Can you clarify? What are you doing in a web app that causes recompilation, but doesn't cause dotnet-watch to show console output?

**Comment by natemcmaster** [comment]
Closing due to lack of details. We can reopen if you can provide more details.
