### ISSUE TITLE
Where is the source of dotnet-dev-certs?

### ISSUE THREAD

**Issue by John0King** [aspnet/DotNetTools#447]
I'm trying to learn how microsoft create cerificat .
I can not find the `Microsoft.AspNetCore.Certificates.Generation.Sources` package . Is it open source?

and I can not find the `dotnet-dev-certs` on my local machine, 
I've searched `%userprofile%\\.nuget\packages\.tools` and `C:\Program Files\dotnet\sdk\NuGetFallbackFolder\.tools`

**Comment by natemcmaster** [comment]
`Microsoft.AspNetCore.Certificates.Generation.Sources` is here: https://github.com/aspnet/Common/tree/2.1.0/shared/Microsoft.AspNetCore.Certificates.Generation.Sources. 

The dotnet-dev-certs tool is bundled in the SDK. By default, it is not installed as a NuGet package. `C:\Program Files\dotnet\sdk\2.1.300\DotNetTools\dotnet-dev-certs\`.
