### ISSUE TITLE
“dotnet watch run” DOESN'T auto refreshes your site

### ISSUE THREAD

**Issue by flauberjp** [aspnet/DotNetTools#449]
I use to create SPA using Angular2+, and the command usage of _ng server --open_  is very common , it basically start your web site and keep it updated with you change it, and that is done on the fly, very handy feature, increases a lot the dev productivity. **_donet watch_ can act like that?** If not, please provide.

I was able to get a workaround for it following these two tutorials in sequece:

1. [“ng server” for .NET? Meet “dotnet watch run”](https://flauberjp.wordpress.com/2018/06/02/ng-server-for-net-meet-dotnet-watch-run/)

2. [How “dotnet watch run” auto refreshes your site?](https://flauberjp.wordpress.com/2018/06/06/how-dotnet-watch-run-auto-refreshes-your-site/)

**Comment by natemcmaster** [comment]
`dotnet watch run` only supports reloading the server process. It doesn't communicate with your browser when updates to static assets, like javascript files, are available. For that, I would recommend using JavaScript tooling, such as webpack's hot module replacement, or LiveReload. I wrote a demo for doing this with webpack, Typescript, and the WebpackDevMiddleware option in ASP.NET Core (see https://natemcmaster.com/blog/2018/07/05/aspnetcore-hmr/).
