### ISSUE TITLE
What needs to go in "--project" argument?

### ISSUE THREAD

**Issue by 0sinner** [aspnet/DotNetTools#452]
I've looked all over and I can't seem to find the right documentation for something simple.

My project is organized as such:

* main.sln
* App/
  * App.csproj
* Tests/
  * Tests.csproj

Basically I'm running `dotnet watch test` in the folder where the `.sln` file exists and it gives me the following error:

    watch : Could not find a MSBuild project file in 'X:\Path\To\Project'. Specify which project to use with the --project option.

I will be running this out of a batch file but I don't want to change the working directory, so I tried specifying the requested argument as the following but they ALL give me the same error message:

```
dotnet watch test -p Tests
dotnet watch test -p .\Tests
dotnet watch test -p "Tests"
dotnet watch test -p ".\Tests"
dotnet watch test -pTests
dotnet watch test -p.\Tests
dotnet watch test "-pTests"
dotnet watch test "-p.\Tests"
dotnet watch test --project Tests
dotnet watch test --project .\Tests
dotnet watch test --project "Tests"
dotnet watch test --project ".\Tests"
dotnet watch test --projectTests
dotnet watch test --project.\Tests
dotnet watch test "--projectTests"
dotnet watch test "--project.\Tests"
dotnet watch test -p Tests\Tests
dotnet watch test -p .\Tests\Tests
dotnet watch test -p "Tests\Tests"
dotnet watch test -p ".\Tests\Tests"
dotnet watch test -pTests\Tests
dotnet watch test -p.\Tests\Tests
dotnet watch test "-pTests\Tests"
dotnet watch test "-p.\Tests\Tests"
dotnet watch test --project Tests\Tests
dotnet watch test --project .\Tests\Tests
dotnet watch test --project "Tests\Tests"
dotnet watch test --project ".\Tests\Tests"
dotnet watch test --projectTests\Tests
dotnet watch test --project.\Tests\Tests
dotnet watch test "--projectTests\Tests"
dotnet watch test "--project.\Tests\Tests"
dotnet watch test -p Tests\Tests.csproj
dotnet watch test -p .\Tests\Tests.csproj
dotnet watch test -p "Tests\Tests.csproj"
dotnet watch test -p ".\Tests\Tests.csproj"
dotnet watch test -pTests\Tests.csproj
dotnet watch test -p.\Tests\Tests.csproj
dotnet watch test "-pTests\Tests.csproj"
dotnet watch test "-p.\Tests\Tests.csproj"
dotnet watch test --project Tests\Tests.csproj
dotnet watch test --project .\Tests\Tests.csproj
dotnet watch test --project "Tests\Tests.csproj"
dotnet watch test --project ".\Tests\Tests.csproj"
dotnet watch test --projectTests\Tests.csproj
dotnet watch test --project.\Tests\Tests.csproj
dotnet watch test "--projectTests\Tests.csproj"
dotnet watch test "--project.\Tests\Tests.csproj"
```

Is this better documented somewhere I'm just missing? Am I using the parameter incorrectly?

NOTE: I am running this on Windows dotnet core 2.1.x currently.

EDIT: So I found a way to deal with the batch issues I was having of switching the working directory (`setlocal` to isolate the directory change from the parent context), however I think the issue I'm reporting is still valid. Either the instruction in the error message to use `--project` is incorrect or `--project` is not sufficiently documented anywhere that is easily accessible, or I'm missing something entirely.

**Comment by natemcmaster** [comment]
Try this:
``
dotnet watch -p ./Tests/ test
```

**Comment by 0sinner** [comment]
That worked. Ugh. Sorry. I should have tried the flag before the command. Feel free to close this.

**Comment by natemcmaster** [comment]
Happy to help. `dotnet watch` is tricky because there are arguments on `dotnet watch` and arguments for `dotnet test`, and disambiguating them is not always straightforward. As a general rule, syntax is `dotnet watch {watch options} test {test options}`.

**Comment by toddlangdon** [comment]
Should this work for .sln file?  For example, if I run dotnet watch -p AllMyTests.sln test it doesn't seem to like it:

watch : Started
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...


However, dotnet test AllMyTests.sln works fine...

Thanks in advance
