### ISSUE TITLE
dotnet-watch does not take changes in partial views

### ISSUE THREAD

**Issue by reyou** [aspnet/DotNetTools#459]
**Env**: .net core 2.1
**App**: MVC Web App

To reproduce:
- Create partial view `.\Views\Partials\TopNavigationBar.cshtml`
- Add some HTML elements
-  Render view in `_Layout.cshtml` with `@Html.Partial("../Partials/TopNavigationBar")`
- `dotnet watch run --launch-profile local`

Do some changes in TopNavigationBar.cshtml. Changes remain same.

This happens same if I run it from VS 2017.

**Comment by natemcmaster** [comment]
This is likely a duplicate of https://github.com/aspnet/DotNetTools/issues/152.

By default, dotnet-watch only watches for changes in .cs files. Razor should automatically update views when you update .cshtml files. If it is not, this is likely a bug in Mvc/Razor.

**Comment by reyou** [comment]
@natemcmaster Mvc/Razor picks up changes on regular View files. But for some reason changes in partial views does not appear.

Would you recommend to open this issue under .net core repo?

**Comment by natemcmaster** [comment]
Yeah, I recommend moving this to https://github.com/aspnet/Mvc. That team would know better if this is a known issue or not.

**Comment by reyou** [comment]
Thanks, I did at https://github.com/aspnet/Mvc/issues/8038 closing this one.
