### ISSUE TITLE
Flaky test: RestartProcessThatTerminatesAfterFileChange

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/DotNetTools#472]
This test [fails](http://aspnetci/viewLog.html?buildId=520701&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
System.TimeoutException : The operation at /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:89 timed out after reaching the limit of 30000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineStartsWithAsync(String message, TimeSpan timeout) in /_/test/dotnet-watch.FunctionalTests/AwaitableProcess.cs:line 89
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.GetProcessId() in /_/test/dotnet-watch.FunctionalTests/Scenario/WatchableApp.cs:line 62
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.NoDepsAppTests.RestartProcessThatTerminatesAfterFileChange() in /_/test/dotnet-watch.FunctionalTests/NoDepsAppTests.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
The temporary test folder is /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1
Copying project /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/TestProjects/NoDepsApp to /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp
Restoring msbuild project in NoDepsApp
Project directory: '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp'
Started process 38651: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet restore
  Restoring packages for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/NoDepsApp.csproj...
  Generating MSBuild file /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/obj/NoDepsApp.csproj.nuget.g.props.
  Generating MSBuild file /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/obj/NoDepsApp.csproj.nuget.g.targets.
  Restore completed in 241.95 ms for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/NoDepsApp.csproj.
Process exited 38651
Process exited 38651 with code 0
Building NoDepsApp
Project directory: '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp'
Started process 38838: /mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet build
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 46.46 ms for /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/NoDepsApp.csproj.
  NoDepsApp -> /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/bin/Release/netcoreapp2.2/NoDepsApp.dll
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:02.08
Process exited 38838
Process exited 38838 with code 0
8/1/2018 5:58:52 AM: process start: '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet /mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tool/dotnet-watch.dll run --'
Waiting for output line [msg == 'Started']. Will wait for 120 sec.
8/1/2018 5:58:52 AM: post: 'watch : Running MSBuild target 'GenerateWatchList' on '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/NoDepsApp.csproj''
8/1/2018 5:58:52 AM: recv: 'watch : Running MSBuild target 'GenerateWatchList' on '/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/NoDepsApp.csproj''
8/1/2018 5:58:52 AM: post: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 39064'
8/1/2018 5:58:52 AM: recv: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 39064'
8/1/2018 5:58:53 AM: post: 'watch : Process id 39064 ran for 1178ms'
8/1/2018 5:58:53 AM: recv: 'watch : Process id 39064 ran for 1178ms'
8/1/2018 5:58:53 AM: post: 'watch : Watching 2 file(s) for changes'
8/1/2018 5:58:53 AM: recv: 'watch : Watching 2 file(s) for changes'
8/1/2018 5:58:53 AM: post: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 39224'
8/1/2018 5:58:53 AM: recv: 'watch : Started '/mnt/work/33bdfc1cae7b2a38/.dotnet/dotnet' with process id 39224'
8/1/2018 5:58:53 AM: post: 'watch : Running dotnet with the following arguments: run --'
8/1/2018 5:58:53 AM: recv: 'watch : Running dotnet with the following arguments: run --'
8/1/2018 5:58:53 AM: post: 'watch : Started'
8/1/2018 5:58:53 AM: recv: 'watch : Started'
8/1/2018 5:58:53 AM: post: 'Telemetry is: Disabled'
8/1/2018 5:58:53 AM: recv: 'Telemetry is: Disabled'
8/1/2018 5:58:56 AM: post: 'Running dotnet exec "/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/bin/Release/netcoreapp2.2/NoDepsApp.dll"'
8/1/2018 5:58:56 AM: recv: 'Running dotnet exec "/mnt/work/33bdfc1cae7b2a38/modules/DotNetTools/bin/dotnet-watch.FunctionalTests/Release/netcoreapp2.2/tmp/ulsw05o5.5k1/NoDepsApp/bin/Release/netcoreapp2.2/NoDepsApp.dll"'
8/1/2018 5:58:56 AM: post: 'Process ID: 39472'
8/1/2018 5:58:56 AM: recv: 'Process ID: 39472'
8/1/2018 5:58:56 AM: post: 'Started'
8/1/2018 5:58:56 AM: recv: 'Started'
8/1/2018 5:58:56 AM: post: 'PID = 39472'
8/1/2018 5:58:56 AM: post: 'Exiting'
Waiting for output line [msg.StartsWith('PID =')]. Will wait for 30 sec.
8/1/2018 5:58:56 AM: recv: 'PID = 39472'
Waiting for output line [msg == 'Exiting']. Will wait for 
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RunsWithIterationEnvVariable [failed with about the same error](http://aspnetci/viewLog.html?buildId=522313&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RestartProcessThatTerminatesAfterFileChange [failed with about the same error](http://aspnetci/viewLog.html?buildId=525066&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RunsWithIterationEnvVariable [failed with about the same error](http://aspnetci/viewLog.html?buildId=528350&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RestartProcessThatTerminatesAfterFileChange [failed with about the same error](http://aspnetci/viewLog.html?buildId=530435&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RestartProcessThatTerminatesAfterFileChange [failed with about the same error](http://aspnetci/viewLog.html?buildId=531576&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RestartProcessThatTerminatesAfterFileChange [failed with about the same error](http://aspnetci/viewLog.html?buildId=533567&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
Apparently FileSystemWatcher gets unhappy on some platforms when there are "too many" of them. Can we maybe reduce the parallelization of tests here?

Or, if this test isn't especially crucial to begin with, deleting the test could be fine...

**Comment by natemcmaster** [comment]
That's sort of why I haven't deleted this yet. Restarting when files change is kind of the central feature of dotnet-watch. Seemed bad to deleted the functional test that validates this scenario.

I can try reducing parallelization.

**Comment by Eilon** [comment]
Are there a lot of tests that use an actual FSW? Maybe we could drastically reduce *those* tests, and other tests should just simulate file changes?

**Comment by natemcmaster** [comment]
Yes, there are lots of tests that use FSW. Simulating file changes is going to be an expensive rewrite of basically all of the functional tests.

**Comment by Eilon** [comment]
Can we disable parallelization on the tests in here? Maybe that would help? @HaoK is doing that in another repo that is having FSW pains. If it doesn't slow the tests down too much, I'd say it's a reasonable workaround.

**Comment by Eilon** [comment]
For reference, here's the Identity PR that @HaoK just sent: https://github.com/aspnet/Identity/pull/1944

**Comment by aspnet-hello** [comment]
RestartProcessThatTerminatesAfterFileChange [failed with about the same error](http://aspnetci/viewLog.html?buildId=541196&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
RunsWithIterationEnvVariable [failed with about the same error](http://aspnetci/viewLog.html?buildId=546037&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ChangeFileInDependency [failed with about the same error](http://aspnetci/viewLog.html?buildId=548460&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
RunsWithIterationEnvVariable [failed with about the same error](http://aspnetci/viewLog.html?buildId=550035&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
RunsWithIterationEnvVariable [failed with about the same error](http://aspnetci/viewLog.html?buildId=551788&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
RunsWithIterationEnvVariable [failed with about the same error](http://aspnetci/viewLog.html?buildId=552840&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=558941&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2:
- RunsWithIterationEnvVariable


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559782&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2:
- RunsWithIterationEnvVariable


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=560732&buildTypeId=Releases_22xPublic_UbuntuUniverse) on 2.2:
- RunsWithIterationEnvVariable


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/DotNetTools/pull/497
