### ISSUE TITLE
GetSecretNamesAsync should not create a store if not present

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/DotNetTools#479]
Related issue : https://github.com/Microsoft/visualfsharp/issues/5549#issuecomment-417804122

https://github.com/aspnet/DotNetTools/blob/03e73cc8060ad167056d66ee0bf625dfe6943d82/tooling/Microsoft.VisualStudio.SecretManager/ProjectLocalSecretsManager.cs#L84

This call should be updated to just Get instead of GetorCreate.

**Comment by natemcmaster** [comment]
Closing as the ownership of this project is moving to @vijayrkn's team and they use a different issue tracker.
