### ISSUE TITLE
There was an error trying to clean HTTPS development certificates on this machine. Sequence contains more than one matching element

### ISSUE THREAD

**Issue by itroupansky** [aspnet/DotNetTools#482]
I am running "dotnet dev-certs https --clean" command on my machine and receiving the error I put into the title-"There was an error trying to clean HTTPS development certificates on this machine. Sequence contains more than one matching element". I couldn't find anything pertaining this on the Internet. My OS in Windows 10. Please help.

Thank you,

Irene T.

**Comment by itroupansky** [comment]
I found out that it was 2 references to the same ASP.NET HTTPS certificate in the Trusted root. 
![2cerificates](https://user-images.githubusercontent.com/10565725/45175902-8067ae00-b1dc-11e8-88c2-62a210f3723c.PNG)
I had to delete both manually and then delete the certificate from the personal store.

**Comment by natemcmaster** [comment]
Duplicate of #464? cc @javiercn

**Comment by itroupansky** [comment]
Nope, it had different error message, similar,  but really opposite.

Thanks,

Irene

On Sep 6, 2018, at 14:37, Nate McMaster <notifications@github.com<mailto:notifications@github.com>> wrote:


Duplicate of #464<https://github.com/aspnet/DotNetTools/issues/464>? cc @javiercn<https://github.com/javiercn>

**Comment by javiercn** [comment]
@itroupansky 
Can you check the contents of your current user personal certificate store and your current user trusted root store for localhost certificates?

I think there's a bug on the tool where clean fails when the certificate is not trusted. You could try and trust the certificate with dotnet dev-certs https --trust and then run dotnet dev-certs https --clean work around the issue or remove the certificate manually from the store

**Comment by itroupansky** [comment]
Thanks, @javiercn! The certificate was trusted too much - if you look above, it was twice in Trusted Root. I had to clean it out manually.

Irene
