### ISSUE TITLE
HTTP REPL post command doesn't specify a content type for the request

### ISSUE THREAD

**Issue by danroth27** [aspnet/DotNetTools#486]
If you use the HTTP REPL post command to send a POST request it will suggest some JSON for you to send, but it doesn't set the content type for the request, so the request fails with a 415 Unsupported Media Type error. You can manually specify the content type header as application/json, but if you're going to provide some JSON to send then I think it makes sense to provide the corresponding content type header.

**Comment by danroth27** [comment]
@glennc @mlorbetske

**Comment by shanselman** [comment]
Ya that would be a reasonable default. 

You can either do it for every request

`set header Content-Type application/json`
or just one

`POST -h "Content-Type: application/json"`

**Comment by bradygaster** [comment]
note to @glennc here - talked with @mlorbetske about this, who had done some work here but thinks we may have missed the post method so he'll investigate.

**Comment by mlorbetske** [comment]
This should be fixed by #507
