### ISSUE TITLE
Check for Swagger at /swagger.json per spec

### ISSUE THREAD

**Issue by shanselman** [aspnet/DotNetTools#491]
This seems wrong...

https://github.com/aspnet/DotNetTools/blob/03e73cc8060ad167056d66ee0bf625dfe6943d82/src/Microsoft.HttpRepl/Commands/SetBaseCommand.cs#L55

You're picking this location only because it's the default for .NET Core. 

At a minimum you should also include /swagger.json

**Comment by mlorbetske** [comment]
This should be fixed by #507
