### ISSUE TITLE
Set Header instructions are inconsistent/wrong

### ISSUE THREAD

**Issue by shanselman** [aspnet/DotNetTools#492]
These say : or = https://github.com/aspnet/DotNetTools/blob/03e73cc8060ad167056d66ee0bf625dfe6943d82/src/Microsoft.HttpRepl/Commands/BaseHttpCommand.cs#L101                 

specifically

`shellState.ConsoleManager.Error.WriteLine("Headers must be formatted as {header}={value} or {header}:{value}".SetColor(programState.ErrorColor));`

but only "space" seems to work per 

https://github.com/aspnet/DotNetTools/blob/03e73cc8060ad167056d66ee0bf625dfe6943d82/src/Microsoft.HttpRepl/Commands/SetHeaderCommand.cs#L21

**Comment by mlorbetske** [comment]
On the `--header` option to a get or put request, the `:` or `=` is required, but the `set header` command requires a space separating the header name and value. The help for this was still wrong - indicating that a `:` should separate the name and value for `set header`, so I've got a change fixing that.

**Comment by mlorbetske** [comment]
This should be fixed by #507
