### ISSUE TITLE
ICommandDispatcher.CollectSuggesetions(...) has a typo

### ISSUE THREAD

**Issue by DerAlbertCom** [aspnet/DotNetTools#503]
The title says it all.

https://github.com/aspnet/DotNetTools/blob/9b598446caa060374081b27c00f4c357d064c680/src/Microsoft.Repl/Commanding/ICommandDispatcher.cs#L15

**Comment by mlorbetske** [comment]
Good catch, thanks!

**Comment by mlorbetske** [comment]
This should be fixed by #507
