### ISSUE TITLE
Make it possible to detect when a process is running inside dotnet-watch

### ISSUE THREAD

**Issue by JakeGinnivan** [aspnet/DotNetTools#52]
When using approvaltests or similar it will pop up a diff tool when the test does not match the 'gold' template.

Is there a way to know if running inside dnx-watch? If not would you consider adding an environmental variable called `DNX_WATCH=1` (or `DOTNET_WATCH=1` for rc2 so you can know if you are running inside DNX watch?

**Comment by victorhurdugaci** [comment]
There's no out of the box way to determine if running inside dnx watch, sorry.

One solution would be to check who's the parent process of your process. I haven't tried these solutions, but some people report success with [this method](http://stackoverflow.com/questions/394816/how-to-get-parent-process-in-net-in-managed-way). However, the parent will still be `dnx` so you might have to check the command line args or the loaded modules. Not fun, I know...

**Comment by JakeGinnivan** [comment]
How can I run dnx-watch from source? I would like to submit a PR to add an environmental variable but unsure how to test it.

**Comment by victorhurdugaci** [comment]
We're in the process of converting dnx watch to dotnet watch. If we're going to add this environment variable, it will be dotnet watch and we're not going to port it back to dnx watch.

That being said, the current source code in the dev branch is for dotnet watch. If you want to add that environment variable and then test it then you have to:

1. Build the packages
2. Create a new dotnet (!) project
3. Add `dotnet-watch` to the `tools` section
4. Restore with sources pointing to the folder that has the dotnet watch package
5. Run `dotnet watch` on that project

If you can wait a few more days, I can add that environment variable for you. As a workaround set an environment variable in the console/script invoking dnx-watch. It will be passed all the way to the process being watched.

**Comment by muratg** [comment]
@JakeGinnivan could you clarify your scenario a little more?

**Comment by victorhurdugaci** [comment]
We haven't had the chance to implement this yet so I just wanted to give a workaround. One solution would be to wrap the call to dotnet-watch in a script and set the environment variable there.

**Comment by natemcmaster** [comment]
Remarking for triage. This should be trivial to implement now.

**Comment by natemcmaster** [comment]
Proposed fix in @269. Sorry it took us a year to get to this one.
