### ISSUE TITLE
Add support for launching design time host

### ISSUE THREAD

**Issue by davidfowl** [aspnet/DotNetTools#7]
This would be a great feature as it would speed up compilation dramatically. The idea would be to spin up DTH on the project then pass the port to dnx when launching the application.

**Comment by victorhurdugaci** [comment]
@davidfowl still want this?

**Comment by davidfowl** [comment]
Yes, but it will be very different. It'll likely be a dotnet CLI change to support the roslyn compilation server.

**Comment by victorhurdugaci** [comment]
Close this?

**Comment by natemcmaster** [comment]
In the MSBuild world, is this even a possibility?

**Comment by natemcmaster** [comment]
DNX is dead. Long live DNX issues.

Or not. Closing as this as it's not relevant anymore.
