### ISSUE TITLE
Run any command

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/DotNetTools#87]
There's no reason why dotnet watch couldn't run any command other than `dotnet`. 

The arguments will change a bit but it should do the same: launch an app with arguments

**Comment by tmds** [comment]
+ support dotnet-watch configuration via config file (https://github.com/aspnet/dotnet-watch/issues/114)

**Comment by natemcmaster** [comment]
This issue was originally opened in the project.json era. Removing from backlog for consideration again.

Here's a relative tidbit, now that we've moved to MSBuild. Executing any command could be implemented today by a user by adding a MSBuild target in the project. The command line invocation would look like this:

    dotnet watch msbuild /t:RunMyTarget

FWIW we have a pre-release version of dotnet-watch for MSBuild. (See README.md for install instructions.)

**Comment by natemcmaster** [comment]
Closing as the 1.0.0 version of dotnet-watch is has been released.  Running any command is available by implementing a custom target.

For example,
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <Target Name="CustomCommand">
    <Exec Command="date" />
  </Target>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0" />
  </ItemGroup>
</Project>
```
```   
dotnet restore
dotnet watch msbuild /t:CustomCommand
```

**Comment by tmds** [comment]
@natemcmaster how do you specify: when files matching these patternA change run commandA, and when files matching patternB change run commandB?

**Comment by natemcmaster** [comment]
@tmds dotnet-watch 1.0.0 doesn't support running conditional logic based on which file has changed. Can you open a new issue for that?

**Comment by tmds** [comment]
Can you open a new issue for that?

Perhaps we can re-open https://github.com/aspnet/DotNetTools/issues/114?

> I have a project with a gulp watch to check for typescript changes and a dotnet watch for aspnet core changes.

**Comment by natemcmaster** [comment]
New issue please. #114 doesn't cover conditionally reacting to file changes.
